Changed /myfeeds to go to login page if no user logged in
Seneca-CDOT/telescope pull request #1135
Opened 2020-09-27 18:49 UTC by smilegodly

Added the 'Add yours' link onto the banner which redirects to /myfeeds

## Issue This PR Addresses
Addresses https://github.com/Seneca-CDOT/telescope/issues/981

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
If you are already signed in. When you click on 'Add yours' on the banner, a new tab opens up linking into /myfeeds.
However, If you are not signed in, a new tab opens directing you to the login page to sign in.

If there is anything I need to to fix or add, let me know! :)

![image](https://user-images.githubusercontent.com/35276477/94373006-41ad3500-00d0-11eb-9b18-126dca3a5dfa.png)

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-09-27 18:54 UTC, humphd requested changes
I tested this on https://telescope-amnkygg4a.vercel.app/ and a few things I notice:

- let's always show the underline for the link vs. only when you hover, since I don't think people will discover it otherwise.
- When I click the link, I am taken to https://dev.telescope.cdot.systems/error/?status=404

2020-09-27 19:15 UTC, smilegodly commented
In terms of the link always being underlined I agree and that should be no problem!

As for the link not working I am kind of stuck on that as It's working on my local docker setup..
The code change was in the myfeeds.js
![image](https://user-images.githubusercontent.com/35276477/94373557-22180b80-00d4-11eb-97d4-92509961a87b.png)

2020-09-27 19:46 UTC, smilegodly commented
Could it possibly be because `https://dev.telescope.cdot.systems` doesn't have this redirect code change yet ?
That website still uses the redirects to 404 when the user goes to /myfeeds and is not logged in.

2020-09-27 21:55 UTC, smilegodly commented
https://github.com/Seneca-CDOT/telescope/issues/1137 needs to be resolved before this PR can land.

2020-09-27 21:58 UTC, manekenpix commented
> Could it possibly be because `master` doesn't have this 'redirect to login' code change yet ?
> 
> When you click the "Add Yours" link on the preview server you are directed to `dev.telescope.cdot.systems/myfeeds` which is based on the master branch. The master branch still [does redirects to 404](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/pages/myfeeds.js#L48) when the user goes to /myfeeds and is not logged in.
> 
> https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/pages/myfeeds.js#L48
> 
> That could possibly explain it

@smilegodly 
I just tested your changes (previous version, before you submitted a new PR), and everything seemed to be ok? How are you running telescope on your machine? You don't need the other PR, the way it was before is ok.

2020-09-27 22:11 UTC, manekenpix commented
> #1137 needs to be resolved before this PR can land.

I see what you mean now :+1:

2020-10-01 02:24 UTC, humphd approved these changes

2020-10-01 02:32 UTC, manekenpix approved these changes

2020-10-01 02:33 UTC, merged