Closes #1005: Manage user authentication state using React Context
Seneca-CDOT/telescope pull request #1141
Opened 2020-10-01 05:03 UTC by manekenpix

Co-authored-by: c3ho <calvinho125@gmail.com>

## Issue This PR Addresses

Closes #1005 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
This adds [React Context](https://reactjs.org/docs/context.html) to share the `User` object through our pages and component tree without having to use props.
Because of how our workflow uses redirection for authentication, this PR needs to be tested fully locally, and it probably won't work on `Vercel`.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-10-01 17:06 UTC, c3ho approved these changes
Was able to successfully login using user1/user1pass. Successfully visited pages and had the correct privileges such as adding/deleting feeds.

2020-10-02 01:18 UTC, humphd requested changes

2020-10-02 01:18 UTC, humphd commented on src/frontend/src/components/Login/LoggedIn.jsx
> +  const state = useContext(UserStateContext);
s/state/user/ would be more clear, I think.

2020-10-02 01:18 UTC, humphd commented on src/frontend/src/components/Login/Login.jsx
> +  const state = useContext(UserStateContext);
Same thing here, I think `user` is better.

2020-10-02 01:18 UTC, humphd commented on src/frontend/src/pages/myfeeds.js
> +  const state = useContext(UserStateContext);
`user`

2020-10-02 15:52 UTC, humphd approved these changes

2020-10-02 20:05 UTC, c3ho approved these changes

2020-10-02 20:08 UTC, merged