Added query route tests
Seneca-CDOT/telescope pull request #1161
Opened 2020-10-06 08:10 UTC by c3ho

## Issue This PR Addresses
Part of #1160 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
I added a test for the query route. The only issue I'm having replicating mocking is having the actual search portion fail.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-10-07 14:36 UTC, humphd requested changes

2020-10-07 14:36 UTC, humphd commented on test/query.test.js
> +    const searchTerm = 'I Love Telescope';
```suggestion
    const searchTerm = encodeURIComponent('I Love Telescope');
```

2020-10-07 14:36 UTC, humphd commented on test/query.test.js
> +    expect(res.status).toBe(400);
Let's assert that the length is what we want here so it doesn't get changed in follow-up code (not sure what number you are trying to test exactly).  Also, these aren't "invalid characters" are they?  This test seems to be about maximum length.

```
expect(searchTerm.length).toBeGreaterThan(256);
```

2020-10-10 22:46 UTC, humphd approved these changes

2020-10-11 00:33 UTC, manekenpix approved these changes

2020-10-11 01:05 UTC, merged