fix logged in formatting in mobile view
Seneca-CDOT/telescope pull request #1178
Opened 2020-10-11 06:03 UTC by cindyledev

## Issue This PR Addresses
Fixes #1175 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
This is not the most elegant fix but it does make the mobile view look better.

## Before
![Screenshot 2020-10-10 233704](https://user-images.githubusercontent.com/36822198/95671479-c040b280-0b65-11eb-9922-ad4dc53a64a1.png)
![Screenshot 2020-10-10 234817](https://user-images.githubusercontent.com/36822198/95671480-c171df80-0b65-11eb-97a1-a17443c8e793.png)

## After
![Screenshot 2020-10-11 015716](https://user-images.githubusercontent.com/36822198/95671484-c767c080-0b65-11eb-8572-c7a97bdcd766.png)
![Screenshot 2020-10-11 015640](https://user-images.githubusercontent.com/36822198/95671485-c9318400-0b65-11eb-9488-f9b67a061dbe.png)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-10-11 15:27 UTC, humphd requested changes

2020-10-11 15:27 UTC, humphd commented on src/frontend/src/components/Login/LoggedIn.jsx
> +    width: 250,
`'250px'`

2020-10-15 02:11 UTC, humphd approved these changes

2020-10-15 02:11 UTC, manekenpix approved these changes

2020-10-15 02:12 UTC, merged