Fixes #120: Removed old TODO comment
Seneca-CDOT/telescope pull request #1207
Opened 2020-10-15 20:55 UTC by neilong31

## Issue This PR Addresses

Fixes #1206 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Removed old todo comment that was being unused in src/frontend/src/components/ScrollToTop/ScrollToTop.jsx

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-10-15 21:01 UTC, agarcia-caicedo requested changes

2020-10-15 21:01 UTC, agarcia-caicedo commented on src/frontend/src/components/ScrollToTop/ScrollToTop.jsx
> -      {/* TODO: remove this part of issue: #1206: delete the line and the "anchor" class */}
Both lines 61 and 62 had to be removed, I updated the issue to be more clear, sorry!

2020-10-15 23:36 UTC, humphd commented
@neilong31, so good to see you hacking on Telescope again!  Welcome Back!

2020-10-16 01:54 UTC, neilong31 commented
@humphd haha thanks! Good to be back!

2020-10-16 02:07 UTC, agarcia-caicedo approved these changes

2020-10-16 02:36 UTC, manekenpix approved these changes

2020-10-16 03:15 UTC, merged