Fixes #1190: Added function to remove no content anchors in some posts
Seneca-CDOT/telescope pull request #1209
Opened 2020-10-15 21:42 UTC by tonyvugithub

## Issue This PR Addresses

Fixed #1190 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Added exclusiveFilter option to sanitizeHtml function in sanitize.js . The option removed anchor tags with no content in all headings.

**Before**
![image](https://user-images.githubusercontent.com/427398/95790037-a78ee480-0cac-11eb-9c1e-b97f9b0984e7.png)
***
**After**
![image](https://user-images.githubusercontent.com/55034244/96150504-6da22600-0ed8-11eb-95ec-1610a4bb33e0.png)

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-10-15 23:41 UTC, humphd requested changes
This looks good, but needs a test.  You need to write something very similar to https://github.com/Seneca-CDOT/telescope/blob/master/test/replace-entities.test.js, but you would test cases like:

1. `<a></a>` should get removed
1. `<a></a><a></a><a>should still exist</a>` should only remove third anchor
1. `<a>foo</a>` should not get removed
1. `<a href="http://localhost">localhost</a>` should not get removed
1. `<a href="#abc">abc</a>` should not get removed

etc.

2020-10-15 23:41 UTC, humphd commented on src/backend/utils/html/sanitize.js
> +    exclusiveFilter: (frame) => {
This needs to go in a different PR vs. riding along with this other fix.

2020-10-21 17:45 UTC, tonyvugithub commented
@humphd : I have updated the tests. Ready to merge

2020-10-21 17:50 UTC, tonyvugithub commented
@humphd CI does not like my loop in one of the test, be right back

2020-10-21 18:29 UTC, humphd approved these changes

2020-10-21 18:51 UTC, cindyledev approved these changes

2020-10-21 18:53 UTC, humphd commented
@tonyvugithub can you rebase this onto master and squash this for me and push a new commit?

2020-10-21 19:00 UTC, tonyvugithub commented
@humphd : I have not watched the video for this week yet. Can I do it later tonight?

2020-10-21 19:02 UTC, humphd commented
@tonyvugithub sure, no rush.  Let us know if you need help.

2020-10-21 23:18 UTC, closed without merging