Fixes #881: Removed boxAfterHeader and Box tag
Seneca-CDOT/telescope pull request #1213
Opened 2020-10-20 01:44 UTC by neilong31

Fixes #881 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Removed unused boxAfterHeader style and Box tag in telescope/src/frontend/src/components/SearchPage/SearchPage.jsx

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-10-20 02:33 UTC, c3ho approved these changes

2020-10-20 14:50 UTC, manekenpix requested changes
I think it'd be nice to have some spacing between the header and search
![image](https://user-images.githubusercontent.com/23108901/96603325-e979e500-12c1-11eb-8171-50decc038e6c.png)
Please follow @cindyledev's suggestion in #881 to make changes.

2020-10-22 13:56 UTC, neilong31 commented
Ahhh yes, sorry I've a little more busy. But I'm definitely going to try and make the changes and make a PR some time soon.

2020-11-10 01:04 UTC, humphd commented
@neilong31 how's this coming?  Can we push it over the line soon?

2020-11-10 03:26 UTC, neilong31 commented
Hey, sorry about that! Hopefully, this addresses the suggestion that @cindyledev made in #881

2020-11-11 00:04 UTC, manekenpix requested changes
I don't notice any changes
![image](https://user-images.githubusercontent.com/23108901/98748352-7aa31f80-2387-11eb-86e5-bd91654ff648.png)

2020-11-12 03:00 UTC, neilong31 commented
Sorry, I guess I added the margin in the wrong place! I think it should be good now.

It looks like this now: 
![image](https://user-images.githubusercontent.com/31993023/98890054-22dce500-2469-11eb-8854-8786ceabcf7b.png)

2020-11-12 03:15 UTC, agarcia-caicedo approved these changes

2020-11-12 03:54 UTC, manekenpix approved these changes

2020-11-12 04:35 UTC, merged