Issue 1220
Seneca-CDOT/telescope pull request #1251
Opened 2020-10-29 10:41 UTC by zjjiang2

## Issue This PR Addresses
From Issue #1220 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Added error handling for UX, includes:
1. Post fails to load
![Error](https://user-images.githubusercontent.com/71283454/97555888-15c2ef00-19af-11eb-917f-582dc90006f8.jpg)
2. Post is loading
![Loading](https://user-images.githubusercontent.com/71283454/97555890-15c2ef00-19af-11eb-89a6-7bb3128df931.jpg)
3. Timeline fails to load
![PostsError](https://user-images.githubusercontent.com/71283454/97555891-165b8580-19af-11eb-8a52-c1bb9401ab46.jpg)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-11-04 22:34 UTC, humphd commented
Pinging some reviewers for this.  I like where it's headed, but wording might need tweaks.

2020-11-07 22:30 UTC, cindyledev approved these changes
This is great :D

2020-11-08 06:04 UTC, PedroFonsecaDEV requested changes
Please don't forget to REBASE before and after start working on the requested changes. 
Thanks.

2020-11-08 06:04 UTC, PedroFonsecaDEV commented on src/frontend/src/components/Posts/Posts.jsx
> +    return (
"Unnecessary 'else' after 'return'.eslintno-else-return"

Same as before, use "Quick fix..." and then run prettier until solve the indentation problems.

2020-11-10 01:03 UTC, humphd commented
@zjjiang2 did you want to finish this soon?  You can probably use `npm run eslint-fix` and `npm run prettier` to sort out any issues that are left.

2020-11-10 05:24 UTC, PedroFonsecaDEV commented
@zjjiang2 We still have some minor fixes about imports order: 

[1](https://github.com/Seneca-CDOT/telescope/pull/1251/files#diff-93a6799df46705ffa21a236b1f986e7a4d646a79b3dd6abac9103227dbf64e6dR9) and [2](https://github.com/Seneca-CDOT/telescope/pull/1251/files#diff-60a81f354235758112a505c36bc258df0296b42e471f3b13f32167a65ffb830fR9)

Then I think your PR will be good to go. 

Thanks.

2020-11-10 17:10 UTC, humphd approved these changes
Looks good, with one question about theme colours vs. raw colour values.

2020-11-10 17:10 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +    color: '#B5B5B5',
@cindyledev, @agarcia-caicedo or someone else who knows our theme code: are there theme values we should be using for these colours instead?

2020-11-10 17:10 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +    color: '#B5B5B5',
Same question here re: colours/theme.

2020-11-11 17:40 UTC, c3ho approved these changes

2020-11-11 20:53 UTC, PedroFonsecaDEV approved these changes

2020-11-11 20:58 UTC, PedroFonsecaDEV commented
@manekenpix  
It's good to go. 
Should I click on "Merge pull request" or "Rebase and merge"?

2020-11-11 21:04 UTC, manekenpix commented
Rebasing would be ideal so we can keep a linear history, but I don't trust github solving conflicts so I guess we'll have to merge it as is.

2020-11-11 21:05 UTC, merged