Closes #1193: Feature: add synchronized author/post outline in desktop view
Seneca-CDOT/telescope pull request #1368
Opened 2020-11-15 21:49 UTC by manekenpix

## Issue This PR Addresses
Closes #1193 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This adds an author/post outline in the desktop view.

To keep track of posts entering and leaving the viewport, I used [react-intersection-observer](https://www.npmjs.com/package/react-intersection-observer). I saw the solution used in #1332, but I thought this module provides more functionality and [testing tools](https://www.npmjs.com/package/react-intersection-observer#testing).

For communication between the outline and the timeline components, I used [useContext](https://reactjs.org/docs/hooks-reference.html#usecontext).

Originally, keeping track of posts' headers would've been the best approach to know when a post enters or leaves the viewport, but after all the improvements and the way headers behave now, I had to switch to tracking posts' content. This causes weird behaviours sometimes, but I'm working on solving that.

This is a first iteration that mainly focuses on functionality. Styling can be improved in follow-up pull requests (please don't make me do it.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-11-16 03:39 UTC, humphd commented
This is so cool, I just tried playing with it on Vercel and love it!  I'll try to prioritize reviewing this soon.  Thank you for doing it @manekenpix.

2020-11-16 16:44 UTC, humphd requested changes

2020-11-16 16:44 UTC, humphd commented on src/frontend/src/components/Posts/Outline/Entry.jsx
> +      href={`#inView${post.id}`}
Is there any way that we can clean this up to get rid of the `inView` prefix?  Do we already use the post id asn id elsewhere?

2020-11-16 16:44 UTC, humphd commented on src/frontend/src/components/Posts/Outline/Outline.jsx
> +      {postsUrl && postsUrl.map((post) => post)}
Why bother with `postsUrl.map((post) => post)`?

2020-11-16 16:44 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +  const [isDesktopView, setDesktopView] = useState(true);
We had to do something hacky like this for the sticky header views too.  I wonder if we can abstract this out into a hook or context we (re)use at the top level?

2020-11-16 16:44 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +    setDesktopView(window.innerWidth > 1450);
I think we can do this at much narrower views.  We actually have more space if we shift the timeline of posts to the right and drop the right margin.

2020-11-16 16:44 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +  });
This should have some kind of dependency so we don't keep running it.

2020-11-16 16:44 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +  return isDesktopView ? (
Instead of these long switches, why not make 2 sub components and render one or the other?

2020-11-17 22:09 UTC, PedroFonsecaDEV commented
Following.

2021-01-16 06:42 UTC, manekenpix commented
Since #1316 is the priority now, I think it's a good idea to close this one and try #1193 again once the Gatsby-Next port is completed.

2021-01-16 06:42 UTC, closed without merging