Fixed ##1369: Set up front end testing environment with Nextjs
Seneca-CDOT/telescope pull request #1374
Opened 2020-11-16 15:04 UTC by tonyvugithub

## Issue This PR Addresses
Fixed #1369 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Set up frontend testing environment with Nextjs

Screenshot of successful sample test
![image](https://user-images.githubusercontent.com/55034244/99268409-1ce15e00-27f3-11eb-8c75-79330520d3d9.png)

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-11-16 16:24 UTC, humphd requested changes

2020-11-16 16:24 UTC, humphd commented on src/frontend/package.json
> +    "test": "jest --watchAll",
We don't want to use watch when running `test`, it needs to be a separate command so that CI doesn't hang forever.

2020-11-17 02:44 UTC, tonyvugithub commented
@humphd : I can't make it work. After spending the whole day trying countless solutions that I can find from the internet. It just does not run probably. I talked to @manekenpix about this and we even tried to make changes to circleci config file to get it passed. turned out there might be some conflicts in the settings that confuse the app. My frontend setup runs just fine if I manually CD to the frontend directory and run `npm run test ` the test suite run. But if I run npm run `test-frontend` from root, the test suites did not run and gave me the below error. We suspect that having the frontend in a different repo might solve the issue we are having. 
![image](https://user-images.githubusercontent.com/55034244/99339779-c1e05300-2854-11eb-9b1e-808f82d0fedf.png)

2020-11-17 17:50 UTC, humphd commented
Personally,  I think we should hold off on this.  I think we need to split the next.js fronte-end stuff into a separate repo and then we can do things without cross-polluting the configs for the backend.

2020-11-17 17:59 UTC, tonyvugithub commented
@humphd : That was what we concluded yesterday too. OK then I just close this then? If it will be on another repo

2020-11-17 18:37 UTC, humphd commented
Yeah, let's close for now and follow-up when we move to a new repo layout.

2020-11-17 18:37 UTC, closed without merging