Overwrote css while using the search bar
Seneca-CDOT/telescope pull request #1378
Opened 2020-11-16 21:27 UTC by jiyoungsin

## Issue This PR Addresses

USAGE: Fixes #1375

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

The issue can be read up about [here](https://github.com/Seneca-CDOT/telescope/issues/1375).
When hitting the search bar the header would increase in size. This was the result of changing the font size when we clicked the search button. I have created a quick fix to address this issue by overwriting the css changes in DesktopHeader.jsx.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-11-16 21:36 UTC, jiyoungsin commented
you can check this locally by changing one line of code. 

in Post.jsx line 148  "<a className={classes.link} href={post.feed?.link}>" add a "?" by the post.feed. This is called chaining. This will allow the front end to prevent errors in case of missing properties.

2020-11-16 21:38 UTC, jiyoungsin commented
for an example of chaining you can check out [this](https://js.do/code/530716) my main code or read up about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

2020-11-16 22:16 UTC, PedroFonsecaDEV approved these changes

2020-11-16 23:37 UTC, jiyoungsin commented
@PedroFonsecaDEV Thanks for checking out my PR! I appreciate it.

2020-11-16 23:39 UTC, jiyoungsin commented
@humphd  Thank you for giving my PR some exposure. I was worried I would not get a PR in time for the deadline 😅

2020-11-17 06:09 UTC, agarcia-caicedo commented
Sorry, @jiyoungsin, I'm confused about the pr, does it fix this issue specifically:
![image](https://user-images.githubusercontent.com/49992710/99352894-75574080-2871-11eb-922b-8b1393ffedca.png)

or does it fix something else about the css?

2020-11-17 06:27 UTC, VietnameZe commented
also, make sure to change the color for the hover effect, this color isn't good
![](https://i.imgur.com/JUblgUi.jpg)

2020-11-17 06:41 UTC, VietnameZe commented
> Sorry, @jiyoungsin, I'm confused about the pr, does it fix this issue specifically:
> ![image](https://user-images.githubusercontent.com/49992710/99352894-75574080-2871-11eb-922b-8b1393ffedca.png)
> 
> or does it fix something else about the css?

Same, I don't think the PR fixes the problem

2020-11-17 07:35 UTC, PedroFonsecaDEV commented
@agarcia-caicedo @VietnameZe 
This PR fixes the issue.  From the Vercel build: (Chrome) 
![2020-11-17 02 18 27](https://user-images.githubusercontent.com/60857409/99358494-9c1a7480-287b-11eb-86be-f2f69c915da7.gif)

@VietnameZe the colour theme is not on the scope of the issue or this PR.
But in my browser I don't see the same hover effect that you are experiencing: 

![2020-11-17 02 29 12](https://user-images.githubusercontent.com/60857409/99359307-e2bc9e80-287c-11eb-91b0-9872e7e62616.gif)

2020-11-17 07:42 UTC, PedroFonsecaDEV commented
What is the Zoom of your Browser? Mine is on default 100%.

2020-11-17 07:42 UTC, VietnameZe commented
@PedroFonsecaDEV  try a search term include "react js", other keywords are okay except those terms contained "react js"

2020-11-17 08:00 UTC, PedroFonsecaDEV commented
@agarcia-caicedo @VietnameZe 
This PR fixes the resize issue.  From the Vercel build: (Chrome) 
![2020-11-17 02 18 27](https://user-images.githubusercontent.com/60857409/99358494-9c1a7480-287b-11eb-86be-f2f69c915da7.gif)

@VietnameZe the colour theme is not on the scope of the issue or this PR.
But yes you are right about the hover effect... only when we type "react js", this PR will fix the strange size behaviour bug, but not the bug that changes the "theme" of the page. 

Any idea of what is causing this bug?

2020-11-17 08:01 UTC, PedroFonsecaDEV commented
@agarcia-caicedo @VietnameZe 
This PR fixes the resize issue.  From the Vercel build: (Chrome) 
![2020-11-17 02 18 27](https://user-images.githubusercontent.com/60857409/99358494-9c1a7480-287b-11eb-86be-f2f69c915da7.gif)

@VietnameZe the colour theme is not on the scope of the issue or this PR.
But yes you are right about the hover effect... only when we type "react js", this PR will fix the strange size behaviour bug, but not the bug that changes the "theme" of the page. 

Any idea of what is causing this bug?

2020-11-17 08:33 UTC, PedroFonsecaDEV requested changes
The bugs persist.

2020-11-17 13:27 UTC, jiyoungsin commented
Thank you for looking over this pull request. I will have another look at this on Thursday.

2020-11-17 19:38 UTC, PedroFonsecaDEV commented
So until now, what I know about the bug is:
It's on the search page of DEV (where the bug is worse)and PROD.
It seems to happen only with the string "react js" in any upper and lower case.
If you type another string to search after the "react js" search, the page backs to normal.
When the bug happens, the folder maxcdn.bootstrapcdn.com pop-up on Chrome dev tools.
It only happens when searching for "Post."

2020-11-18 15:43 UTC, humphd commented
@jiyoungsin so to be clear, you're not looking to include this for 0.3?  If you are, it needs to get finished and merged today.

I'm also somewhat unclear what this PR is focused on.  The title of the issue should give more details I think, and a comment clarifying what you're actually fixing and needs to be reviewed.

2020-11-18 22:19 UTC, jiyoungsin commented
I will work on the other two issues I have been tackling tomorrow. I am still bombarded with work from my other courses. I have a pull request that was merged regarding a documentation update (Y).  I will have this pull request fixed by tomorrow at midnight!

2020-11-20 23:53 UTC, humphd commented
I can't reproduce the original bug, does it still exist?

2020-11-21 00:05 UTC, VietnameZe commented
> I can't reproduce the original bug, does it still exist?

@humphd it's okay now, I just closed issue https://github.com/Seneca-CDOT/telescope/issues/1375

2020-11-21 00:09 UTC, closed without merging