add BackToTopButton in searchPage
Seneca-CDOT/telescope pull request #1428
Opened 2020-11-20 00:32 UTC by tianlangwu

## Issue This PR Addresses
fix #1271 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [X] **UI**: Change which improves UI

## Description

Add Back to Top Button in search page. A back to Top button will show up when you have a long search result on the search page. 

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-11-20 23:47 UTC, humphd requested changes
One small change.

2020-11-20 23:47 UTC, humphd commented on src/frontend/src/components/SearchPage/SearchPage.jsx
> +  const classes = useStyles();
Move this to the very top of this function.

2020-11-21 01:31 UTC, humphd requested changes

2020-11-21 01:31 UTC, humphd commented on src/frontend/src/components/SearchPage/SearchPage.jsx
> +  const classes = useStyles();
Sorry, above this comment:

```js
const SearchPage = () => {
  const classes = useStyles();

  // We synchronize the `text` and `filter` values to the URL's query string
  // via `textParam` and `filterParam`. The <SearchBar> UI uses our internal
  // state values, and the <SearchResults> only update on page load or when
  // the user submits the form.
  ...
```

2020-11-21 01:38 UTC, tianlangwu commented on src/frontend/src/components/SearchPage/SearchPage.jsx
> +  const classes = useStyles();
oh, yes, My bad.

2020-11-21 14:44 UTC, humphd approved these changes

2020-11-22 01:22 UTC, jossiey approved these changes
It works as expected

2020-11-22 01:29 UTC, merged