Added Dynamic Favicon Notification for New Posts
Seneca-CDOT/telescope pull request #1441
Opened 2020-11-22 09:55 UTC by zjjiang2

## Issue This PR Addresses
Fixes Issue #966: Notification Favicon

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This Pull Request adds the new feature of notifying the user of new posts when tabbed out of the site by changing the Favicon into a notification Favicon whenever the page is automatically updated. 
![image](https://user-images.githubusercontent.com/71283454/99900639-da9a9f80-2c7e-11eb-8c0f-d61121900229.png)
![image](https://user-images.githubusercontent.com/71283454/99900641-e1291700-2c7e-11eb-931f-282ccad4222f.png)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2020-11-22 09:56 UTC, zjjiang2 commented
There are definitely improvements to be made on this, please let me know!

2020-11-22 15:07 UTC, humphd requested changes
This isn't building on CI: ` WebpackError: ReferenceError: self is not defined`

Can you try running `npm run build` locally and figure it out?

2020-11-22 15:11 UTC, humphd requested changes

2020-11-22 15:11 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +      if (isVisible) {
This should be happening in the `useFaviconBadge` hook, we don't need to expose it here.  You should just set it to false, and let the hook figure out when to show/hide it.

2020-11-22 15:11 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +      ref.current = value[0][0].id;
This will blow up if `value` doesn't exist, or `value[0]` isn't an array.  We should wrap it in a try/catch.

2020-11-22 15:11 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +const usePrevious = (value) => {
It looks like you're trying to do https://usehooks.com/usePrevious/ here, but not correctly.  Your effect is going to run non-stop, you need to add a dependency array.  Also, this hook needs to be in `hooks/` and also, it probably exists as something we can import.

2020-11-22 22:55 UTC, humphd commented on src/frontend/src/components/Posts/Posts.jsx
> +const usePrevious = (value) => {
Available in https://github.com/streamich/react-use/blob/master/docs/usePrevious.md

2020-11-23 06:31 UTC, PedroFonsecaDEV commented
I'm waiting to review when the PR passes all the tests. 

But at first glance, I think we had/have a pop-up that appears when new content is available, not sure. 
cc @c3ho

2020-11-23 07:47 UTC, c3ho commented
We have one but that's not a favicon, I think reddit uses both. A snackbar when browsing on the page to let you know there's new content + change to the fav icon so you'll know if you're on another tab

2020-11-24 20:25 UTC, humphd approved these changes
I've been collaborating on this with @zjjiang2 this week, and we've got this to a good place (it all works for my tests).

To test this, here's what you need to do:

1. Pull this branch and run `npm install`
1. Modify line 32 of src/frontend/src/components/Posts/Posts.jsx to `const REFRESH_INTERVAL = 3000;` so it updates more often (otherwise, you have to wait 5 mins at a time)
1. Run the backend with `npm start`
1. Run the frontend with `npm run develop`
1. Open http://localhost:8000, confirm the favicon is normal (our Telescope logo)
1. Open a second tab (i.e., don't have the app focused)
1. In a terminal, clear your redis DB with `npx redis-cli flushall`
1. Wait a min or so and confirm that the favicon for the Telescope app in the other tab gets a red dot in it (i.e., new posts have been downloaded)
1. Click into the Telescope tab, make sure the red dot disappears

2020-11-24 21:17 UTC, PedroFonsecaDEV approved these changes

2020-11-24 21:20 UTC, merged