Port AdminButton from gatsby to next.js
Seneca-CDOT/telescope pull request #1515
Opened 2020-12-11 00:01 UTC by sonechca

## Issue This PR Addresses

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-01-16 14:02 UTC, tonyvugithub commented
@sonechca : Hi there, we are in the process of reviewing these migrated to Next PRs. Just wonder if you are still interested to work on this as we would like you to make some changes to your PR. Please let us know in case you decided to drop this then we can assign the issue to others. Thank you.

2021-01-20 14:09 UTC, humphd requested changes
A couple of things to do, and also, please `git mv` the file src/frontend/next/src/components/AdminButtons/AdminButtons.tsx to src/frontend/next/src/components/AdminButtons.tsx (i.e., get rid of the directory).

2021-01-20 14:09 UTC, humphd commented on src/frontend/next/src/contexts/User/UserContext/index.js
> +import { createContext } from 'react';
Delete this file.

2021-01-20 14:09 UTC, humphd commented on src/frontend/next/src/components/AdminButtons/AdminButtons.tsx
> +import { UserStateContext } from '../../contexts/User/UserContext';
Once #1521 lands (hopefully soon), we can change this to:

```ts
import { useUser } from '../UserProvider';
```

2021-01-20 14:09 UTC, humphd commented on src/frontend/next/src/components/AdminButtons/AdminButtons.tsx
> +  const user = useContext(UserStateContext);
This can become:

```ts
const user = useUser();
```

2021-01-20 14:10 UTC, humphd commented
Also, you need a rebase on `master` to pickup the `package.json` changes:

```
git checkout master
git pull upstream master
git checkout Port-AdminButtons
git rebase master
...fix conflicts...
git add src/frontend/next/package.json
git rebase --continue
```

2021-01-22 16:59 UTC, humphd commented
@sonechca what's happening here?  I'd like to get this shipped today.

2021-01-22 19:09 UTC, humphd commented
We decided to move this to 1.6, and we'll take the work in #1504 to add a dummy AdminButtons component for now.

2021-01-29 14:01 UTC, yuanLeeMidori commented
close by #1619

2021-01-29 14:01 UTC, closed without merging