Add Initial Project Diagram Drawing
Seneca-CDOT/telescope pull request #1537
Opened 2021-01-15 23:47 UTC by birtony

## Issue This PR Addresses

Fixes #1535 - Project documentation is missing initial project scribble performed by @humphd 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR adds the following image (initial project diagram) to the repository:
![initialProjectDiagram](https://user-images.githubusercontent.com/33902374/104788558-7ec13400-5760-11eb-96ec-90275ebb2028.jpeg)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-01-16 10:28 UTC, PedroFonsecaDEV requested changes
That is going to be a really nice feature to have.
Could you please draw the diagram on a digital platform? (e.g., draw.io)
So we can update it as the project scales.

2021-01-16 11:20 UTC, PedroFonsecaDEV approved these changes

2021-01-16 22:55 UTC, chrispinkney approved these changes

2021-01-16 22:56 UTC, chrispinkney commented
> 
> 
> That is going to be a really nice feature to have.
> Could you please draw the diagram on a digital platform? (e.g., draw.io)
> So we can update it as the project scales.
> 
> cc @manekenpix

I'm trying to do that often for my capstone, though I'm fairly confident that the image is highly outdated haha. It'd be fun to host a group call on teams and redesign one though.

2021-01-17 00:30 UTC, cindyledev commented
This 5 minute fix is starting conversations :)

2021-01-17 01:44 UTC, merged