Providing Theme object to the whole app
Seneca-CDOT/telescope pull request #1574
Opened 2021-01-20 18:20 UTC by tonyvugithub

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Provided the theme object to the whole app in `_app.tsx` using `ThemeProvider`

2021-01-20 18:26 UTC, birtony submitted a review, later dismissed

2021-01-20 19:29 UTC, humphd commented
```
> Build error occurred
1:21:07 PM: Error: Minified Material-UI error #4; visit https://material-ui.com/production-error/?code=4&args[]=A400 for the full message.
1:21:07 PM:     at augmentColor (/opt/build/repo/src/frontend/next/node_modules/@material-ui/core/styles/createPalette.js:192:13)
1:21:07 PM:     at createPalette (/opt/build/repo/src/frontend/next/node_modules/@material-ui/core/styles/createPalette.js:228:16)
1:21:07 PM:     at createMuiTheme (/opt/build/repo/src/frontend/next/node_modules/@material-ui/core/styles/createMuiTheme.js:46:44)
1:21:07 PM:     at Module.hUgY (/opt/build/repo/src/frontend/next/.next/server/pages/_app.js:267:43)
1:21:07 PM:     at __webpack_require__ (/opt/build/repo/src/frontend/next/.next/server/pages/_app.js:23:31)
1:21:07 PM:     at Object.0 (/opt/build/repo/src/frontend/next/.next/server/pages/_app.js:106:18)
1:21:07 PM:     at __webpack_require__ (/opt/build/repo/src/frontend/next/.next/server/pages/_app.js:23:31)
1:21:07 PM:     at /opt/build/repo/src/frontend/next/.next/server/pages/_app.js:91:18
1:21:07 PM:     at Object.<anonymous> (/opt/build/repo/src/frontend/next/.next/server/pages/_app.js:94:10)
1:21:07 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
1:21:07 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
1:21:07 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
1:21:07 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
1:21:07 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
1:21:07 PM:     at require (internal/modules/cjs/helpers.js:72:18)
1:21:07 PM:     at hasCustomGetInitialProps (/opt/build/repo/src/frontend/next/node_modules/next/dist/build/utils.js:26:1231)
```

2021-01-21 23:06 UTC, humphd requested changes
Why did you delete the frontend readme?

2021-01-21 23:06 UTC, humphd commented on src/frontend/next/next.config.js
> +  reactStrictMode: false,
I'd leave a comment above this line to indicate that we can't switch over (yet) due to MUI style issues, otherwise someone will do it.

2021-01-21 23:06 UTC, humphd commented on src/frontend/next/src/pages/_document.tsx
> +        // eslint-disable-next-line react/no-danger
We can do this in the global eslint config, since we'll need it for post content too.

2021-01-21 23:49 UTC, humphd requested changes
SO MUCH BETTER!

one small change...

2021-01-21 23:49 UTC, humphd commented on src/frontend/next/src/theme/lightTheme.ts
> +/* export const darkTheme: Theme = createMuiTheme({
Can you move this comment block to a `darkTheme.ts` file, so it exists, and we can file another issue to hook it up later?  Having it buried in a comment isn't great.

2021-01-21 23:54 UTC, humphd approved these changes
Looks good, but let's not lose that dark theme code.  Can we file an issue and copy/paste it there or something?

2021-01-21 23:55 UTC, manekenpix approved these changes

2021-01-22 00:01 UTC, merged