Fixes #1468: Port error page from Gatsby to Nextjs
Seneca-CDOT/telescope pull request #1746
Opened 2021-02-16 03:18 UTC by rjayroso

## Issue This PR Addresses
Fixes #1468 
Closes #1506 (Old PR for same issue)

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
This PR takes over and continues the work of #1506 to port the error page from Gatsby to Next.js. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

## Notes
As it stands, the error page port needs a replacement for the old `Pagebase` component which is being addressed in issue #1691. Furthermore, parts of the codebase may need to be changed to support Typescript - specifically:

```typescript
const errorMessages = new Proxy(
  {
    400: 'We did not understand the request!',
    401: 'You are not authorized to view this page!',
    403: 'Access is not allowed for the requested page!',
    404: 'We could not find what you were looking for!',
    405: 'Method is not allowed!',
  },
  {
    get: (object, property) => {
      return property in object ? object[property] : 'Something went wrong!';
    },
  }
);
```
The code above from the original Gatsby error page essentially creates a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) for an undefined object containing the status codes and subsequent error messages.  
  
However, this object cannot be indexed as originally intended, meaning we cannot access the error messages if given the status code:
```typescript
// From my understanding, this is how it's intended to work in JavaScript
let status = 400;

console.log(errorMessages[status]); // Will print out 'We did not understand the request!'

// ---------------------------------------------------------------------------------------------
// How the code currently behaves in TypeScript

let status: Number = 400;

console.log(errorMessages[status]); // we cannot do this, errorMessages[status] will give the following error below

/*
Element implicitly has an 'any' type because expression of type 'number' can't be used to index type 
'{ 400: string; 401: string; 403: string; 404: string; 405: string; }'.

  No index signature with a parameter of type 'number' was found on type 
'{ 400: string; 401: string; 403: string; 404: string; 405: string; }'.
*/
```
Moreover, changing the `type` of `status` to `String` or `Number` will yield the same type of complaint.

2021-02-16 14:12 UTC, HyperTHD commented
@rjayroso Use the FeedHash interface in `interfaces.ts` as a reference for how you can fix the typing for Proxy. You're going to need to do that so since the proxy object looks like it needs to be indexed. We'll hopefully get an update on PageBase in today's meeting so that you won't have that linting issue since it doesn't exist yet

2021-02-16 15:38 UTC, rjayroso commented
> @rjayroso Use the FeedHash interface in `interfaces.ts` as a reference for how you can fix the typing for Proxy. You're going to need to do that so since the proxy object looks like it needs to be indexed. We'll hopefully get an update on PageBase in today's meeting so that you won't have that linting issue since it doesn't exist yet

Thank you so much, I'll take a look at that right now and see. I'll be working on the layout later today

2021-02-17 00:17 UTC, humphd requested changes

2021-02-17 00:17 UTC, humphd commented on src/frontend/next/src/pages/error.tsx
> +function CreateInnerErrorContent({ message, status }: ErrorProps) {
Drop the `Create-` prefix: `InnerErrorContent` is probably good.

2021-02-17 00:17 UTC, humphd commented on src/frontend/next/src/pages/error.tsx
> +  const baseURL = 'https://telescope.cdot.systems/';
We need to get this from `config.ts` so we can configure it for local vs. staging vs. prod.

2021-02-18 23:05 UTC, rjayroso reviewed
Dropped "Create" from `CreateInnerErrorContent` to `InnerErrorContent`, and added an import from `config.ts` to take the URL from there

2021-02-18 23:55 UTC, humphd requested changes
Let's get this rebased so vercel can build and deploy it for testing.

2021-02-18 23:55 UTC, humphd commented on src/frontend/next/src/pages/error.tsx
> +      top: '0vh',
`top: 0` (no units on 0, since 0px == 0vh == 0% etc)

2021-02-19 15:46 UTC, humphd approved these changes

2021-02-19 17:06 UTC, chrispinkney approved these changes
Awesome job man!

2021-02-19 18:04 UTC, UsernameHasBeenChanged100Times approved these changes

2021-02-19 19:10 UTC, merged