Fixes #1815: Spotify playlists within an iframe are not sanitized
Seneca-CDOT/telescope pull request #1817
Opened 2021-02-22 20:46 UTC by HyperTHD

## Issue This PR Addresses
Fixes #1815 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Some users may include spotify playlists in their blog posts. This gets included via an iFrame tag. We previously did not allow this, and they would not appear. This PR addresses that by including `open.spotify.com` to the list of allowed iFrame sources as well as `cdn.embedly.com` if it's used to embed any iframes from the list of allowed sources in the future. Tests were updated to account for this. For the latter link, refer to the final test within (https://github.com/Seneca-CDOT/telescope/blob/master/test/fix-iframe-width.test.js) since the latter link essentially allows an iframe embedded within an iframe. 

To test this, view the deployment link. The latest blog post from Pedro includes a spotify embedded playlist. You should be able to see it display correctly.
## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-02-22 21:25 UTC, humphd requested changes

2021-02-22 21:25 UTC, humphd commented on test/sanitize-html.test.js
> +
Looks good.  We also need a test for cdn.embedly.com

2021-02-23 01:19 UTC, humphd approved these changes
Nice work.

2021-02-23 02:30 UTC, manekenpix approved these changes

2021-02-23 05:12 UTC, merged