Minor About Page CSS Touchup
Seneca-CDOT/telescope pull request #1967
Opened 2021-03-17 14:45 UTC by chrispinkney

## Issue This PR Addresses
None filed, this is a very basic touchup to style the about page. It applies a minor padding fix to about page. I also moved `<AboutFooter>` outside of `<MDXPageBase>` as it was incorrectly being styled as a child.

![Screenshot_2021-03-17 About Us](https://user-images.githubusercontent.com/7242003/111486215-ace5d480-870d-11eb-9498-ba7338d9034e.png)

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
The about page was looking mighty janky with the new sidebar in UI 2.0.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-03-17 14:47 UTC, chrispinkney commented
https://telescope.cdot.systems/about/ 🤮

2021-03-17 14:48 UTC, PedroFonsecaDEV approved these changes

2021-03-17 14:50 UTC, humphd requested changes

2021-03-17 14:50 UTC, humphd commented on src/web/src/pages/layouts/MDXPageBase.tsx
> +        paddingLeft: '150px',
These work well on wide screens, but at narrower viewport sizes, you end up with a ton of whitespace and very little content.  We need some breakpoint magic here (cc @PedroFonsecaDEV, @tonyvugithub, @huynguyez):

![Screen Shot 2021-03-17 at 10 48 52 AM](https://user-images.githubusercontent.com/427398/111487175-84120f00-870e-11eb-85fc-52dd8252426f.png)

2021-03-17 14:54 UTC, birtony requested changes

2021-03-17 14:54 UTC, birtony commented on src/web/src/pages/layouts/MDXPageBase.tsx
>          padding: '3px 5px',
You should combine these into `padding: '3px 150px'`. The current 5px padding is conflicting with what you're adding and is not needed.

2021-03-17 14:54 UTC, birtony commented on src/web/src/pages/layouts/MDXPageBase.tsx
> +        paddingRight: '150px',
Might as well do `padding: '0px 150px'`

2021-03-17 14:54 UTC, birtony commented on src/web/src/pages/layouts/MDXPageBase.tsx
> +        paddingRight: '150px',
Might as well do `padding: '0px 150px'`

2021-03-17 15:03 UTC, chrispinkney commented
Made some changes using `vw` (suggested by @PedroFonsecaDEV, thanks!) and I think this fixes the white space issue.

![Screenshot_2021-03-17 About Us(2)](https://user-images.githubusercontent.com/7242003/111489234-54fc9d00-8710-11eb-9d7e-5f9616d1bba1.png)
![Screenshot_2021-03-17 About Us(1)](https://user-images.githubusercontent.com/7242003/111489238-55953380-8710-11eb-8ee4-461af752bdec.png)
![Screenshot_2021-03-17 About Us(3)](https://user-images.githubusercontent.com/7242003/111489240-55953380-8710-11eb-9ad9-8ca892a92256.png)

2021-03-17 15:08 UTC, PedroFonsecaDEV submitted a review, later dismissed

2021-03-17 15:12 UTC, PedroFonsecaDEV submitted a review, later dismissed

2021-03-17 15:17 UTC, birtony approved these changes
LGTM!

2021-03-17 15:19 UTC, humphd requested changes

2021-03-17 15:19 UTC, humphd commented on src/web/src/pages/layouts/MDXPageBase.tsx
> +        padding: '0vw 0vw 0vw 10vw',
Zero in CSS should be unitless: 0px === 0% === 0em, etc.  Use `0` vs. `0vw`

2021-03-17 15:19 UTC, humphd commented on src/web/src/pages/layouts/MDXPageBase.tsx
> +        padding: '2vw 5vw 0vw 10vw',
I don't understand using vertical units for the width too (`vh` vs `vw`).  Screens aren't square.

2021-03-17 23:02 UTC, humphd requested changes
Almost there, just needs a max-width:

![Screen Shot 2021-03-17 at 7 01 40 PM](https://user-images.githubusercontent.com/427398/111549862-569b8480-8753-11eb-96df-0dd26ec492cc.png)


@PedroFonsecaDEV what's our max-width on the rest of the site?

2021-03-17 23:44 UTC, huynguyez requested changes
Looks good on desktop, but not good on mobile: padding/margin on both side still too much! Also, I noticed overflow part on mobile, make sure you don't use fixed values for width & use breakpoints (sm) for small screen.

2021-03-19 15:01 UTC, chrispinkney commented
@humphd @huynguyez I'm not sure if this is what you guys wanted, sorry if it's not. Let me know!

2021-03-19 15:10 UTC, huynguyez requested changes
Overflow part is still there on mobile.
And again, padding/margin is too much for mobile.

![Screen Shot 2021-03-19 at 11 07 08 AM](https://user-images.githubusercontent.com/10421864/111801430-54e0d680-88a3-11eb-8619-c1f3f93cc593.jpg)

![Screen Shot 2021-03-19 at 11 09 17 AM](https://user-images.githubusercontent.com/10421864/111801760-a0938000-88a3-11eb-86bf-5c2a09ac055a.jpg)

2021-03-19 15:32 UTC, izhuravlev commented
> Overflow part is still there on mobile.
> And again, padding/margin is too much for mobile.
> 
> ![Screen Shot 2021-03-19 at 11 07 08 AM](https://user-images.githubusercontent.com/10421864/111801430-54e0d680-88a3-11eb-8619-c1f3f93cc593.jpg)
> 
> ![Screen Shot 2021-03-19 at 11 09 17 AM](https://user-images.githubusercontent.com/10421864/111801760-a0938000-88a3-11eb-86bf-5c2a09ac055a.jpg)

What's so bad about overflow? I am just not sure what do you want to be fixed regarding this part.

2021-03-19 15:36 UTC, huynguyez commented
@izhuravlev because this is only appear on About page right now, since he tweaking About page, just find way to fix it anyway instead of creating new issue. so you prefer to keep overflow like that?

2021-03-19 15:39 UTC, izhuravlev commented
If you are referring to the edge of text not being straight but wavy - I think it looks good. 

Otherwise I'm not sure what is the problem you are referring to.

2021-03-19 15:53 UTC, huynguyez commented
@izhuravlev There's a ovrflow part on the right of About page. Have you tried to scroll it horizontally from right to left?

2021-03-19 16:58 UTC, PedroFonsecaDEV submitted a review, later dismissed

2021-03-19 20:11 UTC, izhuravlev commented
@huynguyez Would you prefer this more:
![image](https://user-images.githubusercontent.com/36719387/111837058-5abcd300-8908-11eb-8ddf-d4cba04a9b8f.png)
![image](https://user-images.githubusercontent.com/36719387/111837073-60b2b400-8908-11eb-9339-77150ec48b87.png)

2021-03-19 20:46 UTC, chrispinkney commented
Let me know what you guys think

2021-03-20 00:05 UTC, HyperTHD approved these changes
Looks good to me. Think it's in a good place rn

2021-03-20 13:36 UTC, PedroFonsecaDEV approved these changes

2021-03-23 13:07 UTC, rjayroso approved these changes

2021-03-23 14:34 UTC, HyperTHD approved these changes

2021-03-23 14:34 UTC, birtony approved these changes

2021-03-23 14:35 UTC, merged