Fixes SearchResults not displaying posts when searching
Seneca-CDOT/telescope pull request #2012
Opened 2021-03-23 14:15 UTC by HyperTHD

## Issue This PR Addresses
No issue was made for this PR

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR addresses the SearchResults page not properly displaying posts. This page originally used the telescopeURL, which was the original backend url used here. I switched the url to the new posts service url, which will correctly pull in the search microservice url. This bug was found when debugging #1910 and should hopefully help frontend developers working on the frontend search related components

## Checklist

- [c] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-03-23 14:26 UTC, humphd requested changes

2021-03-23 14:26 UTC, humphd commented on src/web/src/components/SearchResults.tsx
> +    `${postsServiceUrl}/query?text=${encodeURIComponent(text)}&filter=${filter}&page=${index}`;
A lot of our current config URLs deal with adding the end-point (i.e., `/query`), see https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/config.ts#L15-L18.  I wonder if we should do the same, so you'd do:

`${postsServiceUrl}?text=${encodeURIComponent(text)}&filter=${filter}&page=${index}`;

2021-03-23 15:33 UTC, humphd requested changes

2021-03-23 15:33 UTC, humphd commented on src/web/src/components/SearchResults.tsx
> +    `${postsServiceUrl}/query?text=${encodeURIComponent(text)}&filter=${filter}&page=${index}`;
Another question: why are we doing a search (/query) at the posts URL?

2021-03-23 15:41 UTC, HyperTHD commented
I done goofed up here. This PR should be switching to the ElasticSearch microservice url, not the posts microservice url. ELK is used here to index posts. This PR will have either be closed, or wait until #1802 is merged

2021-03-23 16:59 UTC, HyperTHD commented
Filed #2014 to successfully link to this issue. This issue can also deal with moving the search service to production/staging since that'll also be needed for the frontend to work

2021-03-26 15:11 UTC, humphd commented
You haven't dealt with my review comments, are you planning to fix?  If not, let's close this.

2021-03-26 17:48 UTC, humphd commented
This is waiting on #1802.  We need the Search service in place before we can update this URL.

2021-04-04 15:11 UTC, humphd reviewed
Did your actual changes get lost here?

2021-04-05 02:51 UTC, HyperTHD commented
> Did your actual changes get lost here?

They did, it's nothing minor since the change I made did not work, but I do need to fix the history here as well

2021-04-09 16:20 UTC, chrispinkney commented
What's going on with this? Think we can get it for today's release?

2021-04-09 17:41 UTC, closed without merging