Fixes #1955: Replace normal hyphen with a non-breaking hyphen
Seneca-CDOT/telescope pull request #2026
Opened 2021-03-25 22:35 UTC by rjayroso

## Issue This PR Addresses
Fixes #1955 

## Type of Change
- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
My name was being broken at the hyphen. I added a line of code to replace all instances of a normal hyphen within the author's name with a [non-breaking hyphen](https://www.toptal.com/designers/htmlarrows/punctuation/non-breaking-hyphen/). 

| Before |
| :---: |
| <img width="201" alt="Screen Shot 2021-03-15 at 8 59 02 PM" src="https://user-images.githubusercontent.com/60857409/111312117-5dcc7080-8635-11eb-83b7-1d600a3bc482.png"> |
| After |
| ![image](https://user-images.githubusercontent.com/48869737/112551887-2ded3d80-8d98-11eb-9a31-6a1df8f02254.png) |

It was [mentioned](https://github.com/Seneca-CDOT/telescope/issues/1955#issuecomment-800256159) in the original issue that a possible fix was to expand the author section, especially since there are other authors with even longer names so I messed around with expanding the width/ giving the authors section a minimum width. This created unintended side effects when resizing the screen to be smaller as the names would begin to clip into the right side of the screen. That being said I'd like to know what you guys think - I can file an issue to better display(?) longer names.

## Checklist
- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

## How to Test
View Vercel deployment and scroll down and see each name, when you see my name you will notice that my last name breaks as a whole instead of in the middle where the hyphen is.

2021-03-25 23:42 UTC, yuanLeeMidori submitted a review, later dismissed

2021-03-26 04:18 UTC, HyperTHD commented
Is there anyway we can test this with the list of names that David provided in the original issue? I know that currently, the vercel deployment for this will use the original backend which we no longer use so the posts won't load. 

@rjayroso Can you run this against the current Telescope backend using a few of those names from the issue this PR closes and add some screenshots regarding them?

2021-03-26 04:19 UTC, HyperTHD requested changes
I'm gonna block this PR until you add some more screenshots using a few of the names David provided in the original issue. Once we know it works for more than just your name, we can merge this one in. No issue with the code, just hard to test with the other names atm since vercel deployment won't load in the posts until search service is in

2021-03-26 05:51 UTC, PedroFonsecaDEV approved these changes
<img width="60" alt="Screen Shot 2021-03-26 at 1 46 33 AM" src="https://user-images.githubusercontent.com/60857409/112588044-20a27400-8dd5-11eb-9548-6dbb8ed20f42.png">

NON-BREAKING HYPHEN: 
HEX CODE:`&#x2011`

To test, you need to copy the char and paste it in some [code converter](https://r12a.github.io/app-conversion/) and check the HEX CODE. 

Nice work @rjayroso

2021-03-26 14:58 UTC, humphd requested changes
I'm not sure this is a good solution.  First, the way you're doing your code, if you really want to make that replacement, you should use a unicode character vs. literal, since it's very hard to see that hyphen as being different in JS.

However, this breaks how hyphenation works on the web.  [Hyphens are supposed to provide wrap opportunities to the browser](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/), and removing that seems wrong.

I would expand the width of this container.  We have more room on the page, why limit it to such a narrow region?

2021-03-28 19:14 UTC, rjayroso commented
> I'm not sure this is a good solution. First, the way you're doing your code, if you really want to make that replacement, you should use a unicode character vs. literal, since it's very hard to see that hyphen as being different in JS.
> 
> However, this breaks how hyphenation works on the web. [Hyphens are supposed to provide wrap opportunities to the browser](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/), and removing that seems wrong.
> 
> I would expand the width of this container. We have more room on the page, why limit it to such a narrow region?

I've tried using CSS but it seems to me that, to make the hyphen non-breakable you will also subject the whole author name to also be unbreakable.

What I currently have up is: I've expanded the author info container and changed the string literal to a Unicode character and looks like so:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48869737/112764652-9118e300-8fd7-11eb-9d77-62468d8a001e.gif)

Though, I was thinking should we remove the Unicode stuff altogether? It won't solve the original hyphen-break issue but would still allow for the accommodation of larger names without messing with how the hyphen behaves.

2021-03-29 18:48 UTC, humphd requested changes
Personally, I think the wrapping here when we hit a narrower size is fine.  If you think it's wrong, we should change our breakpoint logic so we hide the name, or switch to putting the name on the top vs. right-hand side sooner.

2021-03-29 18:48 UTC, humphd commented on src/web/src/components/Posts/PostInfo.tsx
> +  // Replace normal hyphen with non-breaking hyphen
agree, let's not do this.  I don't think it's a good idea.

2021-03-30 13:32 UTC, humphd approved these changes

2021-03-30 13:38 UTC, chrispinkney submitted a review, later dismissed

2021-03-30 14:30 UTC, humphd approved these changes

2021-03-30 14:31 UTC, HyperTHD approved these changes

2021-03-30 14:32 UTC, merged