Fixes #2016: Increases jest e2e timeout seconds
Seneca-CDOT/telescope pull request #2059
Opened 2021-03-31 16:46 UTC by HyperTHD

## Issue This PR Addresses
This PR closes #2016 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Our e2e tests were failing due to the github actions vm possibly not having enough time to run the e2e tests. This PR adds an additional 5000 seconds to a total of 10000 milliseconds to run the e2e tests. Since the issue is in the e2e tests ran during a push or PR, we'll know if it works by looking at the e2e tests when this PR is made or whenever it gets updated/rebased. 

I started with 10000 just to be safe, and can easily increment this if the time is not enough.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-03-31 18:49 UTC, humphd requested changes
You have 10 commits in here for what should be a single-line change to one file.  The change to SearchResults.tsx shouldn't be in there.  Can you please fix your history?

Also `100,000` is pretty long, I'd try `30,000` to start.

2021-04-01 00:36 UTC, humphd requested changes
Still seeing 10 commits.

2021-04-01 00:36 UTC, humphd commented on jest-playwright.config.js
> +    launchTime: 30000,
`launchTimeout` is what it needs, I think vs. `launchTime`.

2021-04-01 02:16 UTC, birtony commented
@HyperTHD  try the following:
1. Check if you have your upstream configured correctly pointing to `git@github.com:Seneca-CDOT/telescope.git`: `git remote -v`
2. Get the latest code from the main telescope repo and reset your master branch, then check git history:
```bash
git checkout master
git fetch upstream
git reset --hard upstream/master
git log
```
2a. At this point, you may also want to push the updated master branch to your forked repo to update it there as well: `git push -f origin master` (optional)
3. Create a temporary branch and `cherry-pick` commits needed (I think you only have one for that PR - `e474969bb57d4f9368ebad7cd9a06fd9058dfcfe`). If you need to look up hashes of commits that you need to keep, checkout to `issue-2016` branch and see `git log` or use https://github.com/Seneca-CDOT/telescope/pull/2059/commits. Note that you need to be on the `tmp-branch` when you do a cherry-pick.
```bash
git checkout -b tmp-branch
git cherry-pick e474969bb57d4f9368ebad7cd9a06fd9058dfcfe <any-additional-hashes-space-separated>
```
4. Check git history and make sure all of your changes for this PR are there: `git log`
5. Remove branch issue-2016 locally: `git branch -D issue-2016`
6. Rename tmp-branch to issue-2016: `git branch -m "issue-2016"`
7. Force push to remote: `git push -f origin issue-2016`

2021-04-01 14:58 UTC, humphd commented
Please fix your git history:

```
git checkout master
git pull upstream master
git diff master jest-playwright.config.js jest.config.e2e.js > 2059.diff
git checkout -B issue-2016 master
git apply 2059.diff
```

2021-04-04 14:01 UTC, closed without merging

2021-04-06 17:37 UTC, humphd commented
This got closed and never fixed.  I still need https://github.com/Seneca-CDOT/telescope/blob/master/jest-playwright.config.js#L11 to get updated.

2021-04-06 23:49 UTC, HyperTHD commented
Another PR is coming up rn to close this issue, accidently closed this in my process of fixing the git history so made a brand new branch and added the changes there