Fixes: #2062: Search bar fires a request on every entered letter
Seneca-CDOT/telescope pull request #2066
Opened 2021-04-01 16:34 UTC by HyperTHD

## Issue This PR Addresses
Fixes #2062 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

I landed #2046 to create a search context. There was a bug I didn't catch where it would create a request on every entered letter instead of just waiting until the user press the enter key or clicks the search button. 

I included the textParam as a value in the SearchProvider which will ensure that SearchResults.tsx uses that property instead of text. Since the text value gets updated everytime a letter is entered, it would fire the async request to search for a post.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-04-01 16:42 UTC, PedroFonsecaDEV requested changes
Go to search and open the network tab. You will notice that you are firing requests even without typing. 
This is another bug that we already fixed a long time ago.

2021-04-01 22:46 UTC, birtony commented
:thinking: 
![image](https://user-images.githubusercontent.com/33902374/113361659-749fe200-931a-11eb-93f2-32e8b3b7f893.png)

2021-04-02 14:25 UTC, HyperTHD commented
> 🤔
> ![image](https://user-images.githubusercontent.com/33902374/113361659-749fe200-931a-11eb-93f2-32e8b3b7f893.png)

That's really weird. The search bar should be calling the search service instead of the posts service anyway so that's not the intended behaviour and is unrelated to this PR. That said, your image is indicating that the posts service was unable to find the post instead of showing the search query server error message which is weird

2021-04-02 21:13 UTC, humphd submitted a review, later dismissed

2021-04-03 15:13 UTC, birtony approved these changes

2021-04-03 20:17 UTC, manekenpix commented
I'm seeing what @PedroFonsecaDEV mentioned in his comment before. It seems that the page keeps sending requests infinitely after hitting enter. We had this bug before, but we fixed it. Maybe it's possible to check the history to see how we fixed it.

cc @humphd @birtony

2021-04-03 20:19 UTC, manekenpix requested changes
I'm seeing what @PedroFonsecaDEV mentioned in his comment before. It seems that the page keeps sending requests infinitely after hitting enter. We had this bug before, but we fixed it. Maybe it's possible to check the history to see how we fixed it.

cc @humphd @birtony

2021-04-03 20:20 UTC, chrispinkney commented
I'm seeing the same requests happening several times over and over again, for example (searched for React):

![image](https://user-images.githubusercontent.com/7242003/113490513-742d5580-9498-11eb-8d80-49ef2f029cc9.png)

2021-04-03 21:11 UTC, HyperTHD commented
> I'm seeing the same requests happening several times over and over again, for example (searched for React):
> 
> ![image](https://user-images.githubusercontent.com/7242003/113490513-742d5580-9498-11eb-8d80-49ef2f029cc9.png)

That's a bug with the wrong service being used. That's unrelated to this PR

2021-04-03 22:24 UTC, humphd commented
I think the Vercel search issue is related to staging/dev running the back-end on the same origin, so `/post:id` works there, but breaks on Vercel.  Microservices are meant to help with this.  See #2012, but we're kind of blocked on other services landing (cc @izhuravlev for Search).

2021-04-04 02:16 UTC, HyperTHD commented
Tested #2075 and the search page was working fine. Gonna wait for that to be merged in so I can rebase that in here and see if that does the trick

2021-04-04 10:19 UTC, PedroFonsecaDEV commented
@HyperTHD don't merge using GitHub. Merge in your local machine then push the rebase version. 

```
git checkout master
git pull upstream master
git checkout SearchBugFix
git rebase master
```

2021-04-06 20:42 UTC, humphd submitted a review, later dismissed
Works great.

2021-04-07 00:17 UTC, humphd approved these changes

2021-04-07 02:12 UTC, manekenpix submitted a review, later dismissed

2021-04-07 02:47 UTC, merged