Switched to react testing library for FE tests
Seneca-CDOT/telescope pull request #2122
Opened 2021-04-10 23:19 UTC by birtony

## Issue This PR Addresses

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
With using [`@testing-library/react`](https://www.npmjs.com/package/@testing-library/react), I was able to create a snapshot test for the `AboutFooter` component, which didn't work with `react-test-renderer`. I suggest that we switch to the first one instead.I have also added `jest-update` script to launch tests and update any outdated snapshots.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-04-10 23:36 UTC, humphd requested changes
Nice, a few small things.

2021-04-10 23:36 UTC, humphd commented on package.json
> +    "jest-update": "cross-env MOCK_REDIS=1 jest --u",
Include `-c jest.config.js` and also pass `--` at the end, in case you only want to update some subset of tests

2021-04-10 23:36 UTC, humphd commented on package.json
>      "jest-watch": "cross-env MOCK_REDIS=1 jest --watch --",
Reading this, I notice we are missing `-c jest.config.js` in `jest-watch` too, if you want to add.

2021-04-11 14:28 UTC, humphd requested changes

2021-04-11 14:28 UTC, humphd commented on package.json
> +    "jest-update": "cross-env MOCK_REDIS=1 jest -c jest.config.js --u --",
`--u` should either be `--updateSnapshot` or `-u`, see https://jestjs.io/docs/cli#--updatesnapshot.  NOTE: flags like this are always done with a single `-` and single letter, or double '--` and full words.

Let's use `--updateSnapshot` to help document this.

2021-04-11 19:33 UTC, humphd submitted a review, later dismissed

2021-04-11 22:16 UTC, PedroFonsecaDEV approved these changes

2021-04-12 01:55 UTC, merged