Fixes #1938: Updated healthCheck for Posts service
Seneca-CDOT/telescope pull request #2165
Opened 2021-04-16 18:43 UTC by HyperTHD

## Issue This PR Addresses
This PR closes #1938 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

With Redis added to Satellite, I'm able to update the posts service's health check to check if redis is functioning by using the ping function from Redis. This PR also updates the routes for the posts service to use the createError function and call that function using the `next` function as part of the catch.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-04-16 19:24 UTC, humphd requested changes
One small thing and this is ready.

Reading your code, I also realize that we need to add a way to tell the Redis connection to close just as we're shutting down.  Right now we don't expose a hook for this from Satellite, but we can add one.

2021-04-16 19:24 UTC, humphd commented on src/api/posts/src/index.js
>    healthCheck: async () => {
You should return the promise directly

```js
healthCheck: () => redis.ping(),
```

2021-04-16 20:20 UTC, humphd requested changes
I think to get the unit tests to pass, you're going to have to move your `redis` instance out of `index.js` and into its own file?  Not sure, but `redis` being undefined in the tests is odd.

2021-04-16 20:20 UTC, humphd commented on src/api/posts/src/index.js
> +  healthCheck: () => {
You're not returning the promise here.  Should be: `healthCheck: () => redis.ping()`

2021-04-16 21:41 UTC, chrispinkney submitted a review, later dismissed
LGTM besides the nit pointed out by Dave.

2021-04-17 23:00 UTC, HyperTHD commented
@humphd. I might need to wait for the shutdown option to be merged into Satellite. Even in it's own file, redis seems to be undefined which is super weird

2021-04-18 00:11 UTC, humphd commented
I had an epiphany while on a walk today: did we add Redis since the last npm update for Satellite?  We probably need to ship an update that includes it.  I just triggered 1.12.0, which should hit npm within the next 30 mins.  Let's try that and see what happens here.

2021-04-18 13:53 UTC, humphd submitted a review, later dismissed
This looks good.  The only minor nit I have is that you're only exporting a single thing from `redis.js`, so I would `module.exports = redis` instead, so you can `const redis = require('./redis');` and not bother with destructuring.  But it's minor.

I agree, we should do a follow-up to add the shutdown logic for redis too, once that lands.

2021-04-18 14:09 UTC, humphd requested changes

2021-04-18 14:09 UTC, humphd commented on src/api/posts/src/index.js
> +const { redis } = require('./redis');
```js
const = redis = require('./redis');
```

2021-04-18 14:09 UTC, humphd commented on src/api/posts/src/storage.js
> +const { redis } = require('./redis');
Same thing here, no `{...}` anymore.

2021-04-18 14:15 UTC, HyperTHD commented on src/api/posts/src/index.js
> +const { redis } = require('./redis');
You mean 
```js
const redis = require('./redis'); 
```
right?

2021-04-18 14:40 UTC, humphd submitted a review, later dismissed
Perfect.

2021-04-19 02:34 UTC, chrispinkney submitted a review, later dismissed
LGTM

2021-04-19 15:45 UTC, HyperTHD commented
Rebased, @humphd @chrispinkney, let's get this merged in

2021-04-19 15:47 UTC, humphd approved these changes

2021-04-19 16:12 UTC, humphd submitted a review, later dismissed

2021-04-19 16:39 UTC, merged