normalize-url vulnerability fix
Seneca-CDOT/telescope pull request #2258
Opened 2021-06-09 05:13 UTC by PedroFonsecaDEV

## Issue This PR Addresses
Fixes vulnerability on `normalize-url`.
please check: https://github.com/Seneca-CDOT/telescope/security/dependabot/package.json/normalize-url/open

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-06-09 13:27 UTC, humphd requested changes
Can you update all instances of this to 6.0.1?

See https://github.com/Seneca-CDOT/telescope/search?q=normalize-url

2021-06-09 18:44 UTC, PedroFonsecaDEV commented
@humphd sure.

2021-06-10 20:52 UTC, PedroFonsecaDEV commented
Rebasing.

2021-06-10 21:16 UTC, DukeManh approved these changes

2021-06-10 22:09 UTC, manekenpix approved these changes

2021-06-10 22:50 UTC, merged