Fix(front-end): change imports to prevent crashing while building
Seneca-CDOT/telescope pull request #2274
Opened 2021-07-17 20:34 UTC by manekenpix

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
It's seems there's been a change in `Material-UI`, and this change was causing our `dev` build to crash.
This PR fixes the issue.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-07-17 21:44 UTC, PedroFonsecaDEV commented
```
Summary of all failing tests
FAIL src/web/src/components/AboutFooter.test.tsx
  ● renders correctly

    expect(received).toMatchSnapshot()

    Snapshot name: `renders correctly 1`

    - Snapshot  - 2
    + Received  + 2

    @@ -4,14 +4,14 @@
        >
          <div
            class="MuiBox-root MuiBox-root-8"
          >
            <div
    -         class="MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-flex-start MuiGrid-justify-xs-space-between"
    +         class="MuiGrid-root MuiGrid-container MuiGrid-align-items-xs-flex-start MuiGrid-justify-content-xs-space-between"
            >
              <div
    -           class="MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-justify-xs-center MuiGrid-grid-xs-12"
    +           class="MuiGrid-root MuiGrid-container MuiGrid-item MuiGrid-justify-content-xs-center MuiGrid-grid-xs-12"
              >
                <img
                  alt="Telescope Logo"
                  height="60"
                  src="/logo.svg"

       8 | it('renders correctly', () => {
       9 |   const { asFragment } = render(<AboutFooter />);
    > 10 |   expect(asFragment()).toMatchSnapshot();
         |                        ^
      11 | });
      12 |

      at Object.<anonymous> (src/web/src/components/AboutFooter.test.tsx:10:24)


Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `npm run jest -- -u` to update them.

Test Suites: 1 failed, 42 passed, 43 total
Tests:       1 failed, 335 passed, 336 total
Snapshots:   1 failed, 1 passed, 2 total
Time:        32.559 s
Ran all test suites in 7 projects.
```

@manekenpix CI/CD failing.

2021-07-17 21:47 UTC, PedroFonsecaDEV requested changes
Front-end snapshots.

2021-07-17 21:54 UTC, manekenpix commented
@PedroFonsecaDEV I don't think those CI errors are related to my PR. Currently, all the `chore` PRs from `dependabot` have the same issue. We'll have to look into that (but in a separate PR).

2021-07-19 13:26 UTC, humphd approved these changes

2021-07-19 13:34 UTC, PedroFonsecaDEV approved these changes

2021-07-19 15:20 UTC, merged