add  Gitpod doc
Seneca-CDOT/telescope pull request #2474
Opened 2021-11-16 02:25 UTC by DukeManh

Fixes #2429

This adds the Gitpod doc for development on Gitpod.

## Issue This PR Addresses

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-16 02:30 UTC, DukeManh commented on .gitpod.yml
> +    addBadge: false
We already have a badge in Gitpod bot comment.

2021-11-16 13:02 UTC, humphd requested changes
This is excellent to have

2021-11-16 13:02 UTC, humphd commented on docs/gitpod.md
> +   an Issue, Gitpod automatically checks out a new git branch for you to work on.
Add a screenshot of this

2021-11-16 13:02 UTC, humphd commented on docs/gitpod.md
> +   The second tab is free for writing commands.
Same, add a screenshot.  Perhaps 1 will do, and both 4 and 5 can use it.

2021-11-16 13:02 UTC, humphd commented on docs/gitpod.md
> +Gitpod continuously builds all your Git branches like a CI server. Whenever your code changes
The use of "your" is confusing here.  It should be "Telescope's".  You should also mention pull requests.

2021-11-16 13:02 UTC, humphd commented on docs/gitpod.md
> +Within 3 minutes after closing your workspace browser tab, it will be stopped.
Add the note about 50 free hours per month here, so it's clear why this matters.

2021-11-16 13:02 UTC, humphd commented on docs/gitpod.md
> +## Gitpod Pricing
Move this up

2021-11-17 01:17 UTC, DukeManh commented on docs/CONTRIBUTING.md
> +Besides, you can also start an automated development environment and access it
:%s/Besides/However/

2021-11-17 02:42 UTC, DukeManh commented
@humphd Can you re-review please. cc @cindyledev.

2021-11-17 13:36 UTC, humphd approved these changes
Amazing.  We should find a student in the class who wants to develop something on Telescope to use this, and test it out to see if it's missing anything or unclear.

2021-11-18 04:47 UTC, HyperTHD approved these changes

2021-11-18 13:15 UTC, merged