Improve dark mode code colours Fixes #2377
Seneca-CDOT/telescope pull request #2500
Opened 2021-11-19 17:36 UTC by japneetsingh035

## Issue This PR Addresses

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Before:
<img width="1028" alt="Screen Shot 2021-11-19 at 10 45 20 AM" src="https://user-images.githubusercontent.com/47236363/142665998-4f7d3bf7-e19c-46e1-a94e-d3bb5431aa82.png">

After:
<img width="789" alt="Screen Shot 2021-11-19 at 12 35 31 PM" src="https://user-images.githubusercontent.com/47236363/142666484-7e6d7eb2-4b39-414e-a730-8d79b90d5933.png">

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-19 18:02 UTC, AmasiaNalbandian commented
Is the color supposed to change only for dark mode? I am seeing the same color scheme for the light mode also: 
![image](https://user-images.githubusercontent.com/77639637/142670016-05f15861-188d-4cc2-8ffe-afd37a63e507.png)

2021-11-19 18:09 UTC, japneetsingh035 commented
Yes, I am working on the colour scheme to change on the toggle. However, it would require changing all the previous code for highlight.js. So, I made a draft PR to get some help in development.

2021-11-19 18:26 UTC, AmasiaNalbandian commented
> Yes, I am working on the colour scheme to change on the toggle. However, it would require changing all the previous code for highlight.js. So, I made a draft PR to get some help in development.

Can we try something like this? 
https://stackoverflow.com/questions/35762351/correct-way-to-handle-conditional-styling-in-react

Make a conditional in the div for the stylesheet. 
What we can also do it make a variable to toggle the state somewhere [here](https://github.com/Seneca-CDOT/telescope/blob/bff7a86cd25076fee1a7ffa4e4efe9c8f5c16171/src/api/status/public/assets/js/material-dashboard.js#L688), and use this to do the conditional stylesheet.

2021-11-19 18:29 UTC, AmasiaNalbandian commented
This is a better example using the link stylesheets: 
https://stackoverflow.com/questions/43971507/if-else-jsx-using-link-in-react

2021-11-19 18:34 UTC, humphd requested changes
See https://github.com/Seneca-CDOT/telescope/blob/29951b7b60fa33d83e14b05f24d4a4c2722f9ef7/src/web/src/styles/globals.css#L5

We're going to want to have two stylesheets, both from node_modules vs. a cdn, and you will pick the one at runtime to use.

Also, `src/api/status*` isn't the same code as what you're changing for posts.

2021-11-20 21:55 UTC, PedroFonsecaDEV commented on src/web/src/styles/telescope-post-content.css
> +  background: rgb(14, 17, 22);
Hex values, please.

2021-11-28 20:48 UTC, humphd commented
What's the status of this?

2021-11-28 22:37 UTC, japneetsingh035 commented
> What's the status of this?

Well, we can close this PR and will make a new one, once I am done - still working on enabling the dark mode colour.

2021-11-29 00:59 UTC, closed without merging