Issue 2387
Seneca-CDOT/telescope pull request #2503
Opened 2021-11-20 22:04 UTC by LuigiZaccagnini

## Fixes #2387 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

- Updated the root package.json packages. 
- Added a global textEncoder for upgrade jsdom

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-20 23:23 UTC, humphd requested changes
Looks good, tests are all passing.  One small fix.

2021-11-20 23:23 UTC, humphd commented on package.json
> +    "@wordpress/wordcount": "3.2.3",
This should be removed, we don't use it anymore.

2021-11-20 23:23 UTC, humphd commented on package.json
>      "body-parser": "1.19.0",
Filed #2504 to remove this.  We don't need it.

2021-11-21 16:20 UTC, humphd commented on package.json
>      "body-parser": "1.19.0",
You can't remove this withing fixing the other things I mention in #2504.  Please add `body-parser` back, and read review comments more carefully.

2021-11-22 03:05 UTC, humphd requested changes

2021-11-22 03:05 UTC, humphd commented on package.json
> -    "@wordpress/wordcount": "2.15.0",
I told you the wrong thing, I forgot the status service uses this.  We better leave this in.

2021-11-22 03:05 UTC, humphd commented on src/api/status/public/index.html
>    </head>
This file needs to be rebased to pick up the changes in master.

2021-11-22 03:05 UTC, humphd commented on src/backend/data/stats.js
> -const { count } = require('@wordpress/wordcount');
Revert this, sorry about that.

2021-11-22 08:14 UTC, Qiwen-Yu commented
Mark this one as the code review template and example to me.

2021-11-22 13:59 UTC, humphd requested changes

2021-11-22 13:59 UTC, humphd commented on src/backend/data/stats.js
> -const { count } = require('@wordpress/wordcount');
This hasn't been reverted.  Please do

```
git checkout master src/backend/data/stats.js
```

2021-11-22 15:48 UTC, LuigiZaccagnini commented on src/backend/data/stats.js
> -const { count } = require('@wordpress/wordcount');
Just fixed this in the recent commit!

2021-11-22 16:06 UTC, humphd submitted a review, later dismissed

2021-11-23 00:17 UTC, manekenpix reviewed
Please don't merge master into your branch. Revert that change and rebase.

2021-11-23 00:17 UTC, manekenpix requested changes
I'll block this until the PR gets rebased.

2021-11-23 17:21 UTC, humphd submitted a review, later dismissed

2021-11-28 20:48 UTC, humphd commented
Can we get another review on this?

2021-11-28 21:51 UTC, manekenpix approved these changes

2021-11-28 21:53 UTC, humphd commented
@LuigiZaccagnini this needs another rebase:

```sh
git checkout master
git pull upstream master
git checkout issue-2387
git rebase master
# fix merge conflict in package.json
git push origin issue-2387 -f
```

Then ping me so I can review and merge.

2021-12-03 18:22 UTC, humphd commented
What's happening with this?

2021-12-03 20:32 UTC, humphd commented
This is out of date with `package.json`, please fix.

2021-12-03 22:46 UTC, humphd approved these changes
I don't understand the changes to the non-package.json files in this.  Why would prettier change things?

I *think* the rest is good.  I'll add @menghif as a reviewer, since this will cause churn in #2545

2021-12-03 22:50 UTC, LuigiZaccagnini commented
The change in `src/backend/utils/html/dom.js ` was done because the updates in the package.json required an encoder for JSDom. The other changes were prettier as they weren't passing the tests on my end with the rebase.

2021-12-03 22:51 UTC, humphd commented
OK, sounds good.

2021-12-04 16:16 UTC, menghif approved these changes
Looks good! This will impact #2563 but seems like no one is working on it yet.

2021-12-04 16:36 UTC, humphd commented
OK, going to merge this.  FYI @HyperTHD, @manekenpix, in case this breaks staging in ways we haven't tested.

2021-12-04 16:36 UTC, merged