Added a Bull client, and a route /feeds/info to query queue's info
Seneca-CDOT/telescope pull request #2541
Opened 2021-11-28 23:20 UTC by TueNguyen2911

## Issue This PR Addresses
This fixes #2414 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This is draft PR for issue #2414. 

I added a new file `queue.js` that creates and exports a new Bull client with `redis` client connection required from [posts/src/redis.js](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/src/redis.js). I also added a new GET route `feeds/info` to return the queue's information, for now I'm trying to return the number of jobs in the queue. 

I tested the route by running `npm run services:start`, `npm start` first and running `http://localhost/v1/posts/feeds/info` in Postman. However, I haven't got the expected response, please let me know if I'm on the right track!

The response I got was a long loading screen until Bad Gateway

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-29 00:56 UTC, humphd requested changes
You should try running this in GitPod so you don't have to set everything up locally.

Also, you have some lint errors to fix.

2021-11-29 00:56 UTC, humphd commented on src/api/posts/src/routes/feeds.js
> +  res.json({ jobNum: jobNum });
Move this to after line 42, inside the try/catch.  Also, you don't need to repeat `jobNum`:

```js
res.json({ jobNum });
```

2021-11-29 00:56 UTC, humphd commented on src/api/posts/src/routes/feeds.js
> +        message: `Feed not found fore id ${id}`,
Spelling mistake.  Should be `for` not `fore`.

2021-11-29 03:04 UTC, humphd requested changes

2021-11-29 03:04 UTC, humphd commented on src/api/posts/src/routes/feeds.js
> +    jobNum = await queue.count();
Tested on GitPod and this route never seems to return (e.g., I get no response from the server, it just loads forever).  It looks like you're doing it correctly, but there's nothing coming back.

2021-11-29 03:42 UTC, TueNguyen2911 commented
That's what I got for my response as well, the idea seems correct though. I'll look more into it

2021-11-29 13:53 UTC, humphd commented
I suspect that the connection to Redis isn't right somehow (e.g., it's never returning a response).

2021-11-29 23:22 UTC, TueNguyen2911 commented
I'll compare it to the connection in `backend`. Is it possible to log the connection using `logger`?

2021-12-01 05:56 UTC, TueNguyen2911 commented
Hi @humphd, it's not returning any data because the redis clients from `backend` and `posts` have different host. 

The `Redis_URL` in `backend` is `redis:://127.0.0.1` while the one from `satellite`  is `redis://redis:6379`
```js
const redisUrl = process.env.REDIS_URL || 'redis://redis:6379'; // redis.js from satellite
```
https://github.com/Seneca-CDOT/telescope/blob/2359565d11aa045eedadfee2ef72d29f62d87bee/src/backend/lib/redis.js#L9

I tried uncommenting this line ` #REDIS_URL=redis://127.0.0.1 ` from [env.development](https://github.com/Seneca-CDOT/telescope/blob/master/config/env.development) and building the containers again using `docker-compose --env-file ./config/env.development up --build`  but the `host` remain the same.

How do I change the variable `REDIS_URL` to `redis:://127.0.0.1` for satellite's redis.js file

2021-12-01 22:59 UTC, TueNguyen2911 commented
Thank you! I tested it out and the queue from `api` successfully returned stats data. 

If cleaning up the backend is on the list for the next release, it'll be probably late for my release 0.4. Also, I don't think I should touch the configuration of `backend` in this PR (maybe in another PR). 

So how should I move forward from here, should I wait for the other devs' ideas?

2021-12-01 23:01 UTC, manekenpix commented
I'm not sure if this is a `redis` issue since all the other endpoints in `api/posts` rely on the same `redis` client used in the `feeds/info` endpoint, and they all can connect and retrieve data from `redis`.

2021-12-01 23:01 UTC, humphd commented
I agree it's odd that this isn't working, since everything else is running against that same Redis instance.  Is it just your dev setup?

2021-12-02 02:20 UTC, TueNguyen2911 commented
I agree, if it works for other endpoints why not `info`?

It's just when I followed Josue's instructions, the promise from `queue.count()` got resolved once, when `/info` was hit, it still didn't return nothing. I thought changing the `.env` would solve the problem. 

I'll keep trying.

I'll look more into it.

2021-12-02 17:21 UTC, TueNguyen2911 commented
Turns out, I need to provide the `createClient` with type `client` or `subscriber` for queues to share the same connection according to [the documentation](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#queue). 

This is the response I've got for now, `completed` is also 0
```json
{"queueInfo":{"waiting":785,"active":0,"completed":0,"failed":2,"delayed":0,"paused":0,"jobCnt":785}}
```

The reason `completed` is 0 is because of the 2 properties below are true.
https://github.com/Seneca-CDOT/telescope/blob/4b1c07464e79507b29fcabf7a91b3ffafa0068c2/src/backend/feed/queue.js#L29-L30

I also added the 2 options `const redis = Redis({ maxRetriesPerRequest: null, enableReadyCheck: false });` in `redis.js` because I ran into this problem when building the containers. The [CHANGELOG](https://github.com/OptimalBits/bull/blob/develop/CHANGELOG.md#400-2021-10-27) from Bull also mentions this 

![docker-error](https://user-images.githubusercontent.com/58532267/144471023-0617be11-f4ec-4d17-98a5-774e54ea5366.png)

2021-12-02 18:09 UTC, humphd requested changes
We need to add a test for this as well in https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/test/posts.test.js.  We won't have real data, but hopefully it should return something.

I'm fine if you do that test here or in a follow-up PR.  If you do the latter, please file the issue now.

2021-12-02 18:09 UTC, humphd commented on src/api/posts/src/redis.js
> +const redis = Redis({ maxRetriesPerRequest: null, enableReadyCheck: false });
Why these options?

2021-12-02 18:09 UTC, humphd commented on src/api/posts/src/routes/feeds.js
> +    const jobCnt = await queue.count();
You could run these at the same time:

```js
const [jobCnt, queueInfo] = await Promise.all([queue.count(), queue.getJobCounts()]);
```

2021-12-03 05:51 UTC, TueNguyen2911 commented
> We need to add a test for this as well in https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/test/posts.test.js. We won't have real data, but hopefully it should return something.
> 
> I'm fine if you do that test here or in a follow-up PR. If you do the latter, please file the issue now.

I'll add tests in this PR

2021-12-04 00:48 UTC, TueNguyen2911 commented
Hi, for now, `waiting`, `active`, `delayed`, `jobCnt` of the response updates on changes of the queue. `completed`, `failed` are always 0 as completed and failed jobs are removed from the queue. 
```json
{"queueInfo":{"waiting":785,"active":0,"completed":0,"failed":2,"delayed":0,"paused":0,"jobCnt":785}}
```

I try listening for completed queue events but the event is never fired as the `queue` in post is not consumer or producer. I also try adding `'global:completed'`, the event is fired and I've got expected response but it returns error when I try to use `getJobcounts()` on the queue. The error is "Connection in subscriber mode, only subscriber commands may be used"

```javascript
//this event is never fired
queue.on('completed', (job) => {
  console.log(`${job.id} completed`);
});
//this event is fired but get error when trying to use Bull Api on queue
queue.on('global:completed', (jobid) => {
  console.log(`${jobid} completed`);
});
```
I'm not sure how to get `completed` and `active` to update. I need some help on this
Helpful doc links: [bull](https://optimalbits.github.io/bull/), [Global Events](https://github.com/OptimalBits/bull/blob/HEAD/REFERENCE.md#global-events)

2021-12-04 00:50 UTC, humphd commented
This is one reason why doing this in the parser would make the most sense, since that's where we actually manage the queue to begin with.

That said, why don't we start with the items you can get, and do other things in follow ups?

2021-12-04 00:54 UTC, TueNguyen2911 commented
If that's the case, I'd love to work on the parser service later on. 

I'll follow up with what I can get right now. Thanks.

2021-12-05 03:35 UTC, humphd approved these changes

2021-12-06 18:17 UTC, humphd submitted a review, later dismissed

2021-12-06 18:19 UTC, TueNguyen2911 commented
I clicked on Update Branch accidentally.

2021-12-06 18:23 UTC, humphd commented
```
git checkout -B issue-2414 2fd0b98b1090925ca2869cf7a3dbabb97cf770fc
git checkout master
git pull upstream master
git checkout issue-2414
git rebase master
git push origin issue-2414 -f
```

2021-12-06 21:11 UTC, TueNguyen2911 commented
After this got merged, I need to work on the front-end right?

2021-12-06 22:09 UTC, humphd commented
Yup, you can start now if you want, just base your new branch on this branch, and rebase onto master when it lands.

2021-12-06 22:09 UTC, humphd submitted a review, later dismissed

2021-12-06 22:10 UTC, TueNguyen2911 commented
Got it!

2021-12-06 22:13 UTC, HyperTHD submitted a review, later dismissed
Just for reference, Redis was added to Satellite so we should extract it from there. That way, we can also remove `ioredis` and `ioredis-mock` from the posts service. We can do that in another issue though. Nice job

2021-12-10 14:08 UTC, humphd commented
@TueNguyen2911 let's get this in soon, can you rebase and fix the conflict in your package.json?  Ping me when it's ready so I can merge.

2021-12-10 19:17 UTC, humphd requested changes

2021-12-10 19:17 UTC, humphd commented on src/api/posts/package.json
> +    "bull": "^3.20.1",
Because you a dependency, you need to also update the `pnpm` lock file and commit that as well.

2021-12-10 19:49 UTC, merged