Add padding to build log terminal
Seneca-CDOT/telescope pull request #2543
Opened 2021-11-29 15:31 UTC by menghif

## Issue This PR Addresses

Fixes #2534 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Add `1rem` padding to build log terminal.

<img width="227" alt="Screen Shot 2021-11-29 at 10 27 27 AM" src="https://user-images.githubusercontent.com/53121061/143895631-8371efc1-5942-4c5b-a02f-e7fb6699f29a.png">

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-29 15:40 UTC, humphd requested changes

2021-11-29 15:40 UTC, humphd commented on src/api/status/public/css/terminal.css
> +  padding: 1rem;
I think it's too much, `.5rem`?

2021-11-30 15:40 UTC, humphd submitted a review, later dismissed

2021-11-30 16:12 UTC, Andrewnt219 requested changes
Seem like it isn't working. Reproduce:

```diff
// terminal.js
+ terminal.write("Hello world");
```

![image](https://user-images.githubusercontent.com/52666982/144084152-0e9355f3-7a6b-4074-9861-a783180f1cb4.png)

2021-12-02 05:40 UTC, Yoda-Canada reviewed
@menghif I retest your code, and the cursor can display on the second line. However when I put in some letters, they are still on the first line. 
![image](https://user-images.githubusercontent.com/55161917/144362882-94ad6786-f450-408c-a5e0-537baca7781e.png)
![image](https://user-images.githubusercontent.com/55161917/144363057-b0584510-c79f-463f-adb0-55955796519c.png)
The **convertEol: true,** means "When enabled the cursor will be set to the beginning of the next line with every new line. This is equivalent to sending '\r\n' for each '\n'. " Therefore, my point is that **convertEol**  is the issue.
```
const terminal = new Terminal({
  cols: 80,
  rows: 30,
  convertEol: true,
  theme,
});
```

2021-12-02 16:09 UTC, humphd commented
The fix for this is to use CSS to wrap the terminal in a parent element, then set its background to the same colour and include padding.  Here's an example of how I do this on another project:

<img width="1127" alt="Screen Shot 2021-12-02 at 11 08 23 AM" src="https://user-images.githubusercontent.com/427398/144459140-a84dcc77-e139-460b-903c-1024eaf8b829.png">

2021-12-02 17:27 UTC, Andrewnt219 commented
@menghif Add padding to the class ".xterm" works as well. See https://github.com/xtermjs/xterm.js/pull/1208

![image](https://user-images.githubusercontent.com/52666982/144472540-24a7e77a-03ff-4f19-b631-3d24004ddf1f.png)

2021-12-05 03:52 UTC, humphd commented
Can we get an update on this?

2021-12-05 22:30 UTC, menghif commented
Sorry for the delay, @Andrewnt219's fix seems to work well!

2021-12-06 02:04 UTC, Andrewnt219 submitted a review, later dismissed
LGTM 👍.

2021-12-06 16:56 UTC, humphd submitted a review, later dismissed

2021-12-06 16:56 UTC, humphd commented
@menghif squash and rebase this, and I'll merge it!

2021-12-06 17:28 UTC, Andrewnt219 approved these changes

2021-12-06 17:28 UTC, merged

2021-12-06 17:30 UTC, humphd commented
fyi @Yoda-Canada, this might help with your work on styling the terminal as well.