Add share button for posts
Seneca-CDOT/telescope pull request #2548
Opened 2021-11-30 18:59 UTC by tuanthanh2067

## Issue This PR Addresses

Fixes #2117 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-30 20:58 UTC, humphd requested changes
This is very cool!  I think the icon isn't right, since it looks like it's going to take me some where.  Should we use something that's more common for copying (two overlayed squares)?  When I hover over it, I should get a popup that says I can copy the link if I click.  When I click, the "copied" popup is too small.

There are eslint issues to fix.

2021-12-01 00:32 UTC, humphd requested changes
This is way better, nice job.  One thing to fix still: the baseline of the text and the icon don't match:

<img width="184" alt="Screen Shot 2021-11-30 at 7 31 56 PM" src="https://user-images.githubusercontent.com/427398/144149925-a9f23315-3780-4b74-a894-aba3b6b53353.png">

2021-12-01 03:02 UTC, tuanthanh2067 commented
I'm not sure how to fix the baseline thing, any suggestion?

2021-12-01 14:27 UTC, humphd requested changes
I tried to fix the baseline in dev tools, and can't really make it much better.  This icon doesn't want to play nicely with adjacent text.  Let's go with it and maybe someone will solve it later.

One small text fix, and please squash + rebase.

2021-12-01 14:27 UTC, humphd commented on src/web/src/components/Posts/ShareButton.tsx
> +    <ButtonTooltip title="Copy url" arrow placement="top" TransitionComponent={Zoom}>
`Copy URL` (uppercase on URL)

2021-12-01 16:50 UTC, humphd approved these changes
❤️

2021-12-02 15:41 UTC, HyperTHD approved these changes

2021-12-02 15:41 UTC, merged

2021-12-02 16:03 UTC, humphd commented
Man, we need to do a release to get all this good stuff in production!  Great work @tuanthanh2067!