Changed justify to justifyContent instead
Seneca-CDOT/telescope pull request #2552
Opened 2021-11-30 23:22 UTC by nguyenhung15913

## Issue This PR Addresses
Fixes #2550 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Changed <code>justify</code> to <code>justifyContent</code> to needed files.
- Note: In development, my change did not break anything and the site still worked.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-11-30 23:43 UTC, HyperTHD requested changes
Looks good, but you're missing one file.

https://github.com/Seneca-CDOT/telescope/blob/c3cd512bdf9d76e2339f5b93df91886f5d8654b4/src/web/src/components/Posts/Post.tsx#L282

2021-12-01 01:27 UTC, HyperTHD submitted a review, later dismissed

2021-12-01 02:22 UTC, manekenpix submitted a review, later dismissed

2021-12-01 02:29 UTC, DukeManh submitted a review, later dismissed
Very nice.

2021-12-01 02:31 UTC, humphd commented
@nguyenhung15913 please squash this so we can merge it.

2021-12-01 04:13 UTC, manekenpix approved these changes

2021-12-01 04:24 UTC, humphd approved these changes

2021-12-01 04:24 UTC, merged