change auto deployment links
Seneca-CDOT/telescope pull request #2619
Opened 2021-12-16 03:17 UTC by Qiwen-Yu

## Issue This PR Addresses

    USAGE: Fixes #2521

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Fixes #2521 : Recently, added a redirect in our nginx router from :4000 -> /deploy. In this PR, changed the ":4000" to "/deploy" on the places where we are acting as a consumer of the deploy routes vs. defining them. The latter is much nicer from a developer experience point of view.

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2021-12-20 23:19 UTC, AmasiaNalbandian requested changes
Also maybe we can add someplace in the [autodeployment readme](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/README.md) that the route is also accessible through /deploy

2021-12-20 23:19 UTC, AmasiaNalbandian commented on src/api/status/public/js/build-log/api.js
>  // http://localhost:1111/pages/build.html -> http://localhost:4000/:path
Can we change the comment also so we reflect the change and not confuse future readers.

2022-01-13 03:08 UTC, Andrewnt219 requested changes
Can you please also update links in the [readme](https://github.com/Seneca-CDOT/telescope/blob/master/tools/autodeployment/README.md)?

2022-01-14 17:46 UTC, JerryHue commented
This PR has been resumed in #2656.

2022-01-14 17:46 UTC, closed without merging

2022-01-14 20:10 UTC, AmasiaNalbandian commented on src/api/status/src/server.js
> -          `${host.replace(/(^\w+:|^)\/\//, '')}:4000`,
I'm not too certain this change on L29 is required. We changed the route for :4000/log and :4000/deploy. Here it is just using :4000 and doesn't specify if it's for log or deploy. @humphd  What happens when we go to :4000? I haven't gone down this route yet.....