Removed unnecessary tests in release.yml
Seneca-CDOT/telescope pull request #2703
Opened 2022-01-22 00:04 UTC by TueeNguyen

## Issue This PR Addresses

This fixes #2696 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

- Removed unnecessary tests in `release.yml` to make releasing telescope faster. 
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-01-22 01:17 UTC, tpmai22 submitted a review, later dismissed

2022-01-22 01:18 UTC, tpmai22 commented
Lgtm

2022-01-22 02:01 UTC, JiaHua-Zou submitted a review, later dismissed

2022-01-22 02:29 UTC, tpmai22 approved these changes

2022-01-22 14:06 UTC, DukeManh submitted a review, later dismissed
👍

2022-01-22 16:39 UTC, humphd requested changes
Let's update the release.md doc to indicate that no tests will be run.  This means that whoever does the release and makes a new tag, **must** check that current master is green, and that they are tagging the same commit sha as what was built on master.

There's a bit more personal responsibility to doing it this way, if we remove the tests.  We need to be clear about it.

2022-01-22 23:20 UTC, humphd requested changes

2022-01-22 23:20 UTC, humphd commented on docs/release.md
> +1. Make sure your working tree passes all checks (indicated by the green marker) and is clean.
`1. Make sure that the latest commit on `master` is passing CI on GitHub Actions, and that you are sitting on the same commit locally (i.e., `git show` or `git log` and compare the git SHA).`

2022-01-23 14:20 UTC, humphd approved these changes
Looks good, needs a rebase.

2022-01-24 20:16 UTC, cindyledev approved these changes
Looks good. Thank you for doing this :)

2022-01-24 20:43 UTC, humphd approved these changes

2022-01-24 21:17 UTC, DukeManh approved these changes

2022-01-24 21:37 UTC, TueeNguyen commented
Thanks guys!

2022-01-24 21:38 UTC, merged