Draft: Initial draft of workflow
Seneca-CDOT/telescope pull request #2775
Opened 2022-01-29 20:01 UTC by TDDR

## Issue This PR Addresses
Part Of: #1743  

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x]  **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This is an attempt to add a workflow that will build and push our microservice image to the GitHub Container Registry. I am unsure of a couple of lines that I will make a comment on. 

I also do not know how I would test locally. Would I not have to test it right in staging in order for the workflow to trigger?

2022-01-29 20:17 UTC, manekenpix commented on .github/workflows/deploy-feed-discovery-image.yaml
> +      - master
Can you try to change this to the name of the branch you're using and check if this works on your fork?

2022-01-29 21:26 UTC, humphd requested changes

2022-01-29 21:26 UTC, humphd commented on .github/workflows/deploy-feed-discovery-image.yaml
> +        uses: macbre/push-to-ghcr@master
I don't think this action is going to work.  They have a bug with uppercase letters in repo names.

Let's use the official Docker one, https://github.com/docker/build-push-action, and we can use https://github.com/docker/login-action to login to ghcr.io

2022-01-31 01:39 UTC, TDDR commented
Not really sure why these two commits are trying to be added again. 
![image](https://user-images.githubusercontent.com/59970326/151727404-91691ea3-8126-4758-9a95-e4a9482c402b.png)

I thought the rebase went fine 
![image](https://user-images.githubusercontent.com/59970326/151727706-d9144546-a2c3-42de-9e10-71efcc7f4667.png)

but the log shows that the new commits got put on top of mine still
![image](https://user-images.githubusercontent.com/59970326/151727765-d10e45af-5aca-4fb0-97c6-7e91b55a4722.png)

2022-01-31 01:45 UTC, closed without merging

2022-01-31 14:51 UTC, humphd reviewed
I see you closed this, but wanted to give some feedback.  It's looking pretty close.  Nice work.

2022-01-31 14:51 UTC, humphd commented on .github/workflows/deploy-feed-discovery-image.yaml
> +          context: src\api\feed-discovery
Prefer Unix style paths `src/api/feed-discovery`

2022-01-31 14:51 UTC, humphd commented on .github/workflows/deploy-feed-discovery-image.yaml
> +        id: docker_build
I don't think we need an `id`

2022-01-31 14:51 UTC, humphd commented on .github/workflows/deploy-feed-discovery-image.yaml
> +    steps:
Let's also include `buildx`, which gives us some benefits when building multi-stage builds:

```
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
```

See https://docs.docker.com/buildx/working-with-buildx/ for more info.

2022-01-31 14:51 UTC, humphd commented on .github/workflows/deploy-feed-discovery-image.yaml
> +          tags: user/app:latest
Let's tag this slightly different, so we update the `latest` tag for `feed-discovery` to this new image:

```
tags: feed-discovery:latest
```

I also wonder if we should use `feed-discovery:${{github.sha}}` later on.  But we can add that if we need to go back in time to get old versions.

2022-01-31 14:51 UTC, humphd commented on .github/workflows/deploy-feed-discovery-image.yaml
> +on:
We could probably add a path section in here to isolate this to changes in `src/api/feed-discovery` only.  cc @menghif, who just did this for our docs workflows.