Added Cache-Control to build status header
Seneca-CDOT/telescope pull request #2781
Opened 2022-01-30 23:19 UTC by TueeNguyen

## Issue This PR Addresses
Fixes #2515 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

* Added `Cache-Control: no-cache` to build status response header. 

## Testing
I'm not sure if the `Cache-Control` header is added to the response. In `http://localhost/v1/status/build`, checking the network tab, I don't see the `Cache-Control` header in the `Response Headers`
![image](https://user-images.githubusercontent.com/58532267/151722060-8c6c5f85-2d9c-4e1a-843d-0d38a81a8039.png)

To run build log locally, change autodeploymentUrl in src\api\status\public\js\build-log\check-build-status.js
```js
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;  
```
Allow all connectSrc in src\api\status\src\server.js
```js
connectSrc: ["'self'", "*"]
```

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-01-30 23:52 UTC, humphd requested changes

2022-01-30 23:52 UTC, humphd commented on tools/autodeployment/builds.js
> +    res.setHeader('Cache-Control', 'no-cache');
Add this to the Object that has `Content-Type` below (i.e., we already have a spot to include it).

2022-01-31 14:02 UTC, humphd approved these changes

2022-01-31 17:20 UTC, humphd approved these changes

2022-01-31 17:26 UTC, cindyledev approved these changes

2022-01-31 17:35 UTC, merged