Native Base UI library installed
Seneca-CDOT/telescope pull request #2783
Opened 2022-01-31 00:34 UTC by aserputov

## Issue This PR Addresses

Fixes: #2730 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Native Base UI library installed for mobile application. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-01-31 02:44 UTC, TueeNguyen requested changes

2022-01-31 02:44 UTC, TueeNguyen commented on src/mobile/package.json
> +    "native-base": "^3.3.4",
We should pin dependency

2022-01-31 02:48 UTC, TueeNguyen commented
Can you explain the changes in `metro.config.js`

2022-01-31 03:22 UTC, aserputov commented
@TueeNguyen yes. Here is the link abut the [bug]( https://github.com/teambit/envs/issues/143)

2022-02-01 01:58 UTC, closed without merging

2022-02-01 03:33 UTC, AmasiaNalbandian commented
@aserputov Can you let us know what happened? Would be good to know in future if we try to use this again. I don't understand the bug to be honest.

2022-02-01 03:38 UTC, aserputov commented
@AmasiaNalbandian [link](https://github.com/Seneca-CDOT/telescope/issues/2730)

2022-02-01 15:30 UTC, AmasiaNalbandian commented
The PR is being closed because React Native essentially has too many bugs to try and work around, and we have decided it will hinder our progress to have a UI library for 2.6. There seems to be a collective decision to try another package, and that is the direction we are headed in https://github.com/Seneca-CDOT/telescope/issues/2730 the issue to install a UI package for RN.