Add base-install docker image
Seneca-CDOT/telescope pull request #2821
Opened 2022-02-03 18:07 UTC by Kevan-Y

## Issue This PR Addresses
Fixes #2803 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
A draft version of how to have a base file in docker

Need feedback if I'm doing the docker thing correctly.

## Steps to test the PR

   - `cd src/api/`
   - `docker build --tag base-install  . ` (Create a image call base-install)
   - ` cd ../../` (back to root workspace)
   - `pnpm services:start image` (It should start image services and use the local image called base-install)
    
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-04 19:38 UTC, Kevan-Y commented on src/api/Dockerfile
> +RUN npm i -g pnpm
Moved into the base
```yml
RUN apk --no-cache add tini
USER node
```

2022-02-09 15:05 UTC, humphd requested changes

2022-02-09 15:05 UTC, humphd commented on src/api/Dockerfile
> +RUN apk --no-cache add tini
This should be:

```dockerfile
# Tini Entrypoint for Alpine
# util-linux required to optimize builds using multiple cores
RUN apk add --no-cache tini util-linux
ENTRYPOINT [ "/sbin/tini", "--"]
```

By setting an `ENTRYPOINT` you are [defining the default command that gets run in the container](https://docs.docker.com/engine/reference/builder/#entrypoint).  In this case, we're saying, "use tini and have it receive its arguments from what comes next (--)", see https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean.  The `tini` command will take care of initializing our node process for us.

A Dockerfile that uses this as a base would then define a `CMD` to [specify default params to our ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#cmd):

```dockerfile
CMD ["node", "index.js"]
```

So in essence, we're really doing:

```sh
/sbin/tini node index.js
```

But we split it into stages, and the second stage can redefine what the actually arguments are via `CMD`.

2022-02-15 20:12 UTC, Kevan-Y commented
@humphd I think I will revert back the change of DockerFile for the image. I will only push the DockerFile for the base. I will make a follow-up issue for changing the rest of the services later when the base image is hosted into a registry

2022-02-16 15:13 UTC, humphd requested changes
Yes, get rid of the changes to the `image/Dockerfile` until we have this in the registry.  The rest looks good.

2022-02-16 16:37 UTC, DukeManh approved these changes

2022-02-16 18:44 UTC, humphd approved these changes

2022-02-16 18:59 UTC, merged