Fixes #2885 add showLastUpdateAuthor and showLastUpdateTime to Docusaurus config
Seneca-CDOT/telescope pull request #2887
Opened 2022-02-11 21:39 UTC by cindyledev

## Issue This PR Addresses
Fixes #2885

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR adds the last update author and date of each doc

![2022-02-11 16_35_11-Screenshot 2022-02-11 163446](https://user-images.githubusercontent.com/36822198/153673584-df57f6ed-58c7-4bd0-bc6e-29ec6b17f6d1.png)

## Steps to test the PR

To test this PR locally:
1. Add my repository as a remote: `git remote add cindyledev https://github.com/cindyledev/telescope.git`
2. Fetch my branches: `git fetch cindyledev`
3. Checkout my branch: `git checkout issue-2885`
4. Install dependencies using pnpm in root (this will also install dependencies in src/docs: `pnpm install`
5. Change directory to /src/docs: `cd src/docs`
6. Start the server: `pnpm start`
7. Visit localhost:4631 in browser
8. Find any doc on the left-hand side and scroll down to the bottom to see the '_Last updated on **10/14/2018** by **Author**_'

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-11 21:51 UTC, menghif approved these changes
Very nice! I didn't know this was possible.

2022-02-11 21:54 UTC, humphd requested changes

2022-02-11 21:54 UTC, humphd commented on src/docs/package.json
> +    "@docusaurus/plugin-content-docs": "^2.0.0-beta.15",
Remove the `^`

2022-02-12 00:50 UTC, cindyledev commented on src/docs/package.json
> +    "@docusaurus/plugin-content-docs": "^2.0.0-beta.15",
Fixed. Thanks for pointing that out.

2022-02-12 01:01 UTC, menghif approved these changes

2022-02-12 19:13 UTC, joelazwar approved these changes

2022-02-12 21:11 UTC, merged