Use Admonitions in docs
Seneca-CDOT/telescope pull request #2893
Opened 2022-02-12 00:41 UTC by tcvan0707

## Issue This PR Addresses
Fixes #2883 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR adds Admonitions to our docs where appropriate. Here is an example of Admonitions usage in `docs/getting-started/environment-setup`

<img width="879" alt="image" src="https://user-images.githubusercontent.com/69607880/153688650-509b556c-258e-4bcb-89e1-7f6495b03b46.png">

## Steps to test the PR

- Change your current directory to /src/docs by `cd src/docs`
- Run the command `pnpm start`
- Go to `localhost:4631` on your browser

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-12 02:57 UTC, sirinoks requested changes
Some formatting changes, see comments

2022-02-12 02:57 UTC, sirinoks commented on src/docs/docs/getting-started/aws-cloud9.md
> +
Is there a point to have both a word "disclaimer" and the `Info` box? Perhaps remove **Disclaimer:**

2022-02-12 02:57 UTC, sirinoks commented on src/docs/docs/getting-started/aws-cloud9.md
> +
Same here

2022-02-12 02:57 UTC, sirinoks commented on src/docs/docs/getting-started/environment-setup.md
> +    :::
Remove tabs here, because they make the note slightly off to the right and it doesn't align.

2022-02-12 02:57 UTC, sirinoks commented on src/docs/docs/getting-started/environment-setup.md
> +
No need for bold, now that it's outlined with `Info`

2022-02-12 05:33 UTC, tcvan0707 commented
> Some formatting changes, see comments

Hey @sirinoks, I have made some modification based on your reviews. Please check it and let me know if any changes are needed.

2022-02-12 07:05 UTC, sirinoks submitted a review, later dismissed
Looks good!

2022-02-12 18:12 UTC, cindyledev approved these changes
Thanks for doing this. Make sure you take extra care while resolving the conflict in environment-setup.md. That file was modified recently in #2888

2022-02-12 18:46 UTC, joelazwar approved these changes
Looks good ! go ahead and rebase, then squash and merge when you do.

2022-02-13 03:08 UTC, Kevan-Y commented
@tcvan0707 Please fix the conflits

2022-02-13 04:03 UTC, TueeNguyen approved these changes

2022-02-13 04:22 UTC, tpmai22 approved these changes

2022-02-13 05:02 UTC, merged