modify footer ~add links, and changed copyright label
Seneca-CDOT/telescope pull request #2902
Opened 2022-02-12 20:11 UTC by sancodes

## Issue This PR Addresses
Docusaurus footer needs to be updated #2881

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Modify the Footer:
- Added new labels for links, that successfully directs to proper site when clicked.
- Changed Footer's Copyright label
- Changes made passes local test, with screenshot attached below and no updates on documentation as the documentation is still being worked on at the moment. 
<img width="1406" alt="Screen Shot 2022-02-11 at 5 11 22 PM" src="https://user-images.githubusercontent.com/52472550/153726745-c11f6983-5cb2-4888-91d6-ee244d4d8afd.png">

## Steps to test the PR

With Environment Set up to direction to see where the change has been added: 
- Clone the Telescope repository
- Install pnpm globally: npm install -g pnpm
- Install the dependencies: pnpm install (this will also install the dependencies in the Docusaurus website)
- Change directory to src/docs (this is where all the code lives for our Docusaurus website): cd src/docs
- Start the app: pnpm start
- Visit localhost:4631 in your browser.
- Scroll all the way to the bottom of the page, to where the Footer is. 
- You will be able to see various labels that directs to its sites. 
- You can also see updated Footer Copyright label. 

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [X] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-12 22:45 UTC, TueeNguyen commented
Can you rebase instead of merging? You can reset your branch to the commit before your 1st merge commit and do:
1. update your fork 
2. `git checkout master`
3. `git pull origin master`
4. `git checkout footer-enhancement`
4. `git rebase master`

If you have further trouble with rebasing, I'm willing to help

2022-02-12 22:46 UTC, TueeNguyen requested changes
@sancodes Can you rebase instead of merging? You can reset your branch to the commit before your 1st merge commit and do:
1. update your fork 
2. `git checkout master`
3. `git pull origin master`
4. `git checkout footer-enhancement`
4. `git rebase master`

If you have further trouble with rebasing, I'm willing to help

2022-02-12 23:27 UTC, sancodes commented
@TueeNguyen 

so I ran 
1. git reset --hard f6ea868e7f65b32dae5d2d8118463bb6f3db32e1 
2. git checkout master
3. git pull origin master
4. git checkout footer-enhancement
5. git rebase master
6. git push origin footer-enhancement

Then while pushing I get this error. 

![Screen Shot 2022-02-12 at 3 26 32 PM](https://user-images.githubusercontent.com/52472550/153732060-98b11091-6193-4782-890e-b75f5549ecdc.png)


Maybe I did something wrong. Can you help me on this? thank you kindly.

2022-02-12 23:29 UTC, TueeNguyen commented
You're doing it correctly, the SHA commit after you rebase is different than the one you have in this PR, so just do a `git push origin footer-enhancement -f`

This way you're gonna force push it

2022-02-12 23:31 UTC, sancodes commented
@TueeNguyen 

Seems like it worked, Thank you.

Did that meet your requirement?

2022-02-12 23:35 UTC, TueeNguyen commented
I just checked your fork, you haven't `fetch and merge` your fork. Update it and do the steps again without doing `git reset`

2022-02-12 23:44 UTC, sancodes commented
@TueeNguyen 
I just went to the forked version of telescope on my github, clicked on the button that said, 'fetch and merge'
then followed the steps. 

I dont know if I messed up anything. Please let me know, if everything is working fine.

2022-02-12 23:46 UTC, TueeNguyen approved these changes

2022-02-12 23:46 UTC, TueeNguyen commented on src/docs/docusaurus.config.js
> +        copyright: `Copyright © ${new Date().getFullYear()} <br>
Nice!

2022-02-13 00:28 UTC, cindyledev approved these changes
Fantastic work! Thank you so much

2022-02-13 00:30 UTC, merged