Fixes Issue-2767: Windows installation steps to use expo-cli with android studios
Seneca-CDOT/telescope pull request #2920
Opened 2022-02-14 16:23 UTC by AmasiaNalbandian

## Issue This PR Addresses
fixes #2767 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
I was not able to launch expo-cli so easily on my PC so I wrote better instructions for Windows. The link provided says the environment variables are only required for MacOS and Linux users but that is not the case, so I outlined all the steps to do that part. 

## Steps to test the PR
- This ones simple so please just review my steps and see if they make sense. Let me know if you have a different experience on windows. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-14 18:36 UTC, cindyledev submitted a review, later dismissed
I love that you added pictures. They help a lot

2022-02-14 19:22 UTC, menghif requested changes
Looks great! There's missing punctuation at the end of some paragraphs and I would also add a blank line between the paragraphs and the images.

2022-02-14 19:22 UTC, menghif commented on src/docs/docs/tools-and-technologies/react-native.md
> +6. Create a new system variable named `ANDROID_SDK` and the set the value to the path you copied in step 4.
"and then set"
missing an n

2022-02-15 02:58 UTC, cindyledev approved these changes

2022-02-15 02:58 UTC, menghif approved these changes

2022-02-15 02:59 UTC, merged

2022-02-15 03:38 UTC, tpmai22 commented
@AmasiaNalbandian I regconized that I leave a review but forgot to submit it ! Above is my thought on the change maybe we can figure it out in another PR

2022-02-15 03:40 UTC, AmasiaNalbandian commented on src/docs/docs/tools-and-technologies/react-native.md
> +1. [Download Android Studio](https://developer.android.com/studio) using the standard options.
how many people tried this on windows without problems?