[Chore] Remove firebase from development
Seneca-CDOT/telescope pull request #2949
Opened 2022-02-16 04:53 UTC by manekenpix

## Description

Since we're going to use `supabase` as telescope's main database, there's no need for a `firebase` emulator in development.
This PR removes all references to the emulator.
**Note**
There are `firebase` config files that I think will be removed once the `users` service is reworked for `supabase`.

## Steps to test the PR
- Run `docker-compose --env-file ./config/env.development up --build`
- Make sure `telescope` runs as expected

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-16 15:00 UTC, humphd submitted a review, later dismissed
I actually think we can remove the Users service in a follow-up too.  Supabase will be the Users service going forward.

The only thing we need to consider is what our "admin" story is.

2022-02-16 16:11 UTC, DukeManh submitted a review, later dismissed

2022-02-16 16:13 UTC, DukeManh commented
Oh, wait, removing this would break the users test because it uses the firebase emulator. @manekenpix, we should remove the users service in this PR as well.

2022-02-17 01:06 UTC, humphd requested changes
Looks good, one thing.

2022-02-17 01:06 UTC, humphd commented on docker/docker-compose.yml
> -  # users service
Line 100 above, remove the `users` service from the `sso`'s depends:

```
Service 'sso' depends on service 'users' which is undefined.
```

2022-02-17 16:03 UTC, menghif approved these changes

2022-02-17 16:56 UTC, humphd commented
Rebased and fixed in https://github.com/Seneca-CDOT/telescope/commit/aca9f75e2c1359bfa02dfd38f4eb6947f1a05644.

2022-02-17 16:56 UTC, closed without merging