Fixes #2110 - Advanced Search Bar (Work in progress - feedback welcome!)
Seneca-CDOT/telescope pull request #3055
Opened 2022-02-26 07:12 UTC by AmasiaNalbandian

## Issue This PR Addresses
Fixes #2110
Fixes #2894 
Fixes #2618
Fixes #1912 

## Type of Change
Adds the advanced search which will allow users to search by specific fields.

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
We now have the "advanced search" option under the searchbar where you will be able to search by any field of data we collect from the post.

## Steps to test the PR
This is still in progress, but I'd like some feedback as I continue to finish this up. (I am not sure if we are able to create a "dynamic" input for each field or not - not react expert - if you think its possible let me know.). 

1. `pnpm i`
2. `cp config/env.staging .env`
3. `docker-compose --env-file ./config/env.development up --build search elasticsearch redis posts nginx planet`
4. Go to search and try out the advanced search. The general bar now only searches posts - I will add a new PR so it search the word in posts, title AND author.

### Known Deficiencies:
- i need to add the route when we search
- create a submit handler for the advanced search modal
- after submit, and then opening new advanced search we should clear the existing fields??
- the help dialogue is appearing at the wrong times (after a successful advanced search)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-02-26 20:11 UTC, cindyledev commented
Wow look at this UI!

![2022-02-26 15_11_06-Window](https://user-images.githubusercontent.com/36822198/155857712-fa445016-e9b3-4c51-b801-c2fb244c452b.png)

2022-02-26 21:03 UTC, cindyledev commented
This is a really huge PR; it's almost like a full-fledge feature. I would even break this up into multiple PRs; the UI alone is a vast improvement and warrants its own separate PR. Do you think we could have a PR with just the UI and one of the text fields handle the search functionality like our current search bar? We can then iterate in other PRs.

I also wonder if it would make sense to allow the users to use the advanced search on the search page instead of having the "Advanced Search" button open a modal. I feel the modal complicates things.

2022-03-01 01:51 UTC, HyperTHD requested changes
I was heavily involved in the search related stuff last year (Ported most of the search components, wrote search provider, and did constant reviews for the now obsolete advanced search PRs along with helping out the search service), so I'm very much glad that this is not being left for dead. I'm loving the UI alot so no complaints from me on that aspect.

Early testing here shows an issue I made when creating the search provider last year. The state is updating on entering any letter for the author and post title, which shouldn't be occurring. I'm also wondering about whether or not we should provide default values if the advanced search features aren't being used (Make date empty as a default if not used, etc...)

This looks good, but as @cindyledev mentioned, this is very bloated. The UI portion looks nice. The logic part can use some work, but one thing at a time. :)

Main focus for me is the logic parts ofc, the provider and the search results. The separate files for each advanced search feature is more of a nit-pick from me, but is nothing major.

2022-03-01 01:51 UTC, HyperTHD commented on src/web/src/components/SearchResults.tsx
> +  const shouldFetch = () => post.length > 0 || author.length > 1;
This is causing the issue I mentioned btw, need to modify this so that the actual object is not being updated but the param itself.

2022-03-01 01:51 UTC, HyperTHD commented on src/web/src/components/SearchProvider.tsx
> +function getFilter(filter: any) {
Never use any in TS, this is why we use it instead of JS. Assuming it's always going to be a string, we can specify it as such

2022-03-01 01:51 UTC, HyperTHD commented on src/web/src/components/SearchProvider.tsx
>  export interface SearchContextInterface {
I'm curious as to whether we should default the advanced search features here. Might need to look into this possibility more

2022-03-01 01:51 UTC, HyperTHD commented on src/web/src/components/SearchProvider.tsx
> +    console.log('end date', value);
Just a reminder to remove this whenever you merge this PR

2022-03-01 01:51 UTC, HyperTHD commented on src/web/src/components/SearchProvider.tsx
> -        textParam,
Sorta related to the SearchResults bug, `textParam` is different from `text` in the current iteration which is what keeps the state from being updated constantly. Might want to incorporate something similar here

2022-03-08 00:28 UTC, DukeManh requested changes
Thank you for working on it. This is such a large PR, it touches many parts of our search. 
There are a couple of things I can see in the Vercel deployment that needs to be improved/fixed before this can be merged.

- The advance search instruction is removed, it makes the search page looks very empty when we haven't searched anything
- The colors of the dark mode isn't great, for example:
   - The box-shadow of text input seems off
   - The search bar input color is white, not dark
   - Same for the advanced search popup and its content.
 - Instant Search with typing is a cool feature, however, Telescope wants to be more static and it doesn't fit with our style.
 - The close button of the second date input doesn't work
 - The search queries need to be reflected in the URL, for example, if you search for 'some blog', the URL should be `search/?text=some blog`. We had this working already. It is a regression.

2022-03-08 13:42 UTC, rclee91 commented on config/env.development
> +ELASTIC_URL=http://localhost
#2990, which had this same fix, was temporarily closed.
Are you still having the same issue?

2022-03-11 16:50 UTC, AmasiaNalbandian commented
Closing this PR as I have already begun making smaller PRs of the change.
1. https://github.com/Seneca-CDOT/telescope/pull/3164

2022-03-11 16:50 UTC, closed without merging