Update docs for autodeployment routes
Seneca-CDOT/telescope pull request #3101
Opened 2022-03-04 02:50 UTC by dbelokon

## Issue This PR Addresses

Fixes #2546 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [X] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR updates the documentation detailing the new routes for the autodeployment server.

## Steps to test the PR

Nothing to test here... 👀 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [X] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-03-04 14:09 UTC, humphd requested changes
Let's also include links to the new Build Log Dashboard page, where you can see these logs in real-time.

2022-03-07 02:12 UTC, tpmai22 requested changes
I check the links for both `staging` and `production` but they seem to be broken

2022-03-08 11:30 UTC, dbelokon commented
> I check the links for both `staging` and `production` but they seem to be broken

I think this might be a separate issue. Also, I just checked the links to both `staging` and `production` and both of them give a response, so I think they are the actual links.

2022-03-08 12:57 UTC, humphd requested changes
Looks good, one thing to add.

2022-03-08 12:57 UTC, humphd commented on tools/autodeployment/README.md
> +- https://dev.telescope.cdot.systems/deploy/log to check the deployment log,
FYI, there are two more: https://dev.telescope.cdot.systems/deploy/log/previous and https://dev.telescope.cdot.systems/deploy/log/current (https://dev.telescope.cdot.systems/deploy/log redirects to https://dev.telescope.cdot.systems/deploy/log/current).

2022-03-08 12:57 UTC, humphd commented on tools/autodeployment/README.md
> +- https://telescope.cdot.systems/deploy/log to check the deployment log.
Same for this one.

2022-03-10 01:54 UTC, tpmai22 approved these changes
Wish you add this sooner when I was struggled finding my way in `autodeployment` !

2022-03-10 04:45 UTC, tpmai22 commented
I think we are good to go with this @humphd

2022-03-10 15:32 UTC, humphd approved these changes

2022-03-10 15:48 UTC, merged