Write feed-discovery documentation
Seneca-CDOT/telescope pull request #3146
Opened 2022-03-08 20:40 UTC by JerryHue

## Issue This PR Addresses

#203 (this one documents the `feed-discovery` service only)

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [X] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR expands the documentation for the `feed-discovery` service.

The structure used in similar to the [GitHub REST API docs](https://docs.github.com/en/rest).

## Steps to test the PR

1. Pull my changes
2. Go to the docs (`cd src/docs`)
3. Start docusaurus locally (`pnpm start`)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [X] **Documentation**: This PR includes updated/added documentation to user exposed functionality.

2022-03-08 21:55 UTC, humphd requested changes
Love it, a few things.

2022-03-08 21:55 UTC, humphd commented on src/docs/docs/api-services/feed-discovery.md
> +The feed discovery service, as its name states, discovers the feed URL from a blog URL.
Let's add another sentence to indicate that this can also be a YouTube channel, etc.

2022-03-08 21:55 UTC, humphd commented on src/docs/docs/api-services/feed-discovery.md
> +This could be to several reasons. For example,
could be **due** to...

2022-03-08 23:15 UTC, humphd submitted a review, later dismissed

2022-03-08 23:37 UTC, aserputov submitted a review, later dismissed

2022-03-09 00:47 UTC, tpmai22 commented
@JerryHue Let's squash and rebase it and I think we are good to go !

2022-03-09 02:03 UTC, humphd approved these changes

2022-03-09 02:53 UTC, tpmai22 approved these changes

2022-03-09 03:21 UTC, DukeManh approved these changes

2022-03-09 03:29 UTC, merged