Set up ESLint for image service
Seneca-CDOT/telescope pull request #3210
Opened 2022-03-14 18:42 UTC by aserputov

## Issue This PR Addresses

Fixes: #3156 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

## Steps to test the PR

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-03-14 20:08 UTC, cindyledev requested changes

2022-03-15 13:09 UTC, aserputov commented on src/api/image/package.json
> +   "@senecacdot/eslint-config-telescope": "workspace:1.0.0",
`"@senecacdot/eslint-config-telescope": "workspace:1.0.0"` do you mean this one ?

2022-03-15 13:56 UTC, humphd commented
No merging of `master` into PRs please

<img width="860" alt="Screen Shot 2022-03-15 at 9 56 20 AM" src="https://user-images.githubusercontent.com/427398/158393588-d9c6d346-9f5c-4596-b32c-1dd8b767d6c0.png">

2022-03-15 15:23 UTC, cindyledev submitted a review, later dismissed

2022-03-15 16:14 UTC, cindyledev approved these changes

2022-03-16 01:30 UTC, merged