Refactor Dockerfile status
Seneca-CDOT/telescope pull request #3239
Opened 2022-03-17 03:51 UTC by Kevan-Y

## Issue This PR Addresses

Fixes https://github.com/Seneca-CDOT/telescope/issues/1668

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

- Add multi-staging layers
- Add Docker Healthcheck
```bash
❯ docker images | grep refactor/status
refactor/status                                 old                429d3bbd63d3   5 seconds ago       268MB
refactor/status                                 new                638e5f69af08   14 minutes ago      230MB
```

## Steps to test the PR

- `pnpm services:start status`
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-03-17 14:26 UTC, humphd requested changes

2022-03-17 14:26 UTC, humphd commented on src/api/status/Dockerfile
> +RUN apk --no-cache add tini=0.19.0-r0
Rather than doing this, we can use `init: true` in `docker-compose`, which will do the same without installing an extra dependency.

2022-03-17 14:26 UTC, humphd commented on src/api/status/Dockerfile
> +ENTRYPOINT [ "/sbin/tini", "--"]
`init:true` will mean we don't have to bother with this

2022-03-17 14:26 UTC, humphd commented on src/api/status/Dockerfile
> +COPY --from=dependencies-dev /app/package.json ./
Probably copying from the build context makes more sense.

2022-03-17 17:10 UTC, humphd commented
I don't think so.

2022-03-17 23:24 UTC, cindyledev approved these changes

2022-03-17 23:52 UTC, TDDR approved these changes

2022-03-18 00:07 UTC, humphd approved these changes

2022-03-18 01:38 UTC, merged