Add the YouTube banner information for desktop screens
Seneca-CDOT/telescope pull request #3282
Opened 2022-03-22 09:46 UTC by dbelokon

## Issue This PR Addresses

Fixes #2680

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [X] **UI**: Change which improves UI

## Description

This PR adds the front-end for the YouTube banner information. Currently, there are two values that always show negative. This will be addressed in a future PR involving the back-end.

## Steps to test the PR

You can view the changes in vercel autodeployment, however, you can do it locally too.

1. Pull my changes.
2. Use the staging configuration (`cp config/env.staging .env`)
3. Start the front-end (`pnpm dev`)
4. Find the earliest post that is a YouTube video (you can search for the one in the screenshots).

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: ![image](https://user-images.githubusercontent.com/67607236/159441892-fde1d789-d949-48f1-9972-ccc6f48cb5ff.png) 
![image](https://user-images.githubusercontent.com/67607236/159452111-c46bc226-a16f-443c-8fe1-245b4869269c.png)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-03-22 13:25 UTC, AmasiaNalbandian requested changes
Can we change the text colors and font to match the rest of the GitHub side panel? I believe We need Chanel in blue, and then subscribers/views in the grey text/font?

2022-03-23 01:20 UTC, JerryHue requested changes
So, as we have mentioned in the meeting, we can remove the "Share" button (since it is somewhat ambiguous in what it does for the user).

2022-03-23 13:59 UTC, Kevan-Y commented
@dbelokon 
Step I ran:
1. `gh pr checkout 3282`
2. `pnpm i`
3. `cp config/env.staging .env`
4. `pnpm dev`
5. Go to `http://localhost:8000`
6. Search by author `Kevan`
7. Find a post with youtube video.
![image](https://user-images.githubusercontent.com/58233223/159716640-2a8ad037-a32c-4e76-9db2-372e939d2724.png)

Did I do something wrong? I don't see the youtube banner information.

2022-03-23 14:07 UTC, Kevan-Y requested changes

2022-03-23 14:07 UTC, Kevan-Y commented on src/web/src/components/Posts/YouTubeInfo/YouTubeInfoMobile.tsx
> +    </ListSubheader>
When there is no Youtube content I think we shouldn't render that component.
It partially hides Users/orgs avatar when scrolling to another posts.
![image](https://user-images.githubusercontent.com/58233223/159717450-65a6f4ed-6fbc-4b31-9f12-539dc5a69de7.png)

```suggestion
    <ListSubheader component="div" className={classes.root}>
      {!!channelUrl && (
        <div className={classes.YouTubeInfoContainer}>
            <h2 className={classes.YouTubeTitleSection}>
              <a href={channelUrl} className={classes.link}>
                <AiOutlineYoutube className={classes.icon} /> Channel
              </a>
            </h2>
            <p>{subscriberCount} subscribers</p>
            <p>{viewCount} views</p>
       </div>
      )}
    </ListSubheader>
```

2022-03-23 14:12 UTC, Kevan-Y requested changes

2022-03-24 16:53 UTC, AmasiaNalbandian commented
Hello! Please rebase, as the following commit https://github.com/Seneca-CDOT/telescope/commit/6046273fba4b89ce6281f7a34cafbdec7ef222dc has reorganized our file structure!

2022-03-25 04:27 UTC, dbelokon commented
> @dbelokon Step I ran:
> 
> 1. `gh pr checkout 3282`
> 2. `pnpm i`
> 3. `cp config/env.staging .env`
> 4. `pnpm dev`
> 5. Go to `http://localhost:8000`
> 6. Search by author `Kevan`
> 7. Find a post with youtube video.
>    ![image](https://user-images.githubusercontent.com/58233223/159716640-2a8ad037-a32c-4e76-9db2-372e939d2724.png)
> 
> Did I do something wrong? I don't see the youtube banner information.

You didn't do anything wrong, it is just that the YouTube banner is slightly different from the GitHub banner. The main difference is that the YouTube banner will only appear if the post is coming from a YouTube channel feed, and not if the post links to a YouTube video. In my screenshots, I show Dave's YouTube channel which has a feed. If you post a blogpost that links to a YouTube video, that information won't show up because the post itself is a `blogpost` and not a `video` post.

The way I designed it is to appear only about posts that are exclusively from a YouTube channel. I think I should file an issue that redesigns this aspect, because I kind of don't want to have to revamp the whole PR again :(

2022-03-25 05:31 UTC, dbelokon commented
Just so that everybody is aware, I filed an issue (#3322), that addresses @Kevan-Y's point here:



> > @dbelokon Step I ran:
> > 
> > 1. `gh pr checkout 3282`
> > 2. `pnpm i`
> > 3. `cp config/env.staging .env`
> > 4. `pnpm dev`
> > 5. Go to `http://localhost:8000`
> > 6. Search by author `Kevan`
> > 7. Find a post with youtube video.
> >    ![image](https://user-images.githubusercontent.com/58233223/159716640-2a8ad037-a32c-4e76-9db2-372e939d2724.png)
> > 
> > Did I do something wrong? I don't see the youtube banner information.
> 
> You didn't do anything wrong, it is just that the YouTube banner is slightly different from the GitHub banner. The main difference is that the YouTube banner will only appear if the post is coming from a YouTube channel feed, and not if the post links to a YouTube video. In my screenshots, I show Dave's YouTube channel which has a feed. If you post a blogpost that links to a YouTube video, that information won't show up because the post itself is a `blogpost` and not a `video` post.
> 
> The way I designed it is to appear only about posts that are exclusively from a YouTube channel. I think I should file an issue that redesigns this aspect, because I kind of don't want to have to revamp the whole PR again :(

2022-03-25 14:18 UTC, JiaHua-Zou approved these changes
Looks good!

2022-03-25 14:30 UTC, Kevan-Y requested changes
When scrolling down, the yourubeInfo component is hiding user/org.
![image](https://user-images.githubusercontent.com/58233223/160139463-03f56480-9eb0-4ca0-8731-cd24e71e9d1c.png)

2022-03-25 14:32 UTC, dbelokon commented
> When scrolling down, the yourubeInfo component is hiding user/org. ![image](https://user-images.githubusercontent.com/58233223/160139463-03f56480-9eb0-4ca0-8731-cd24e71e9d1c.png)

I actually noticed this when I was writing the PR, and the main problem is how we are currently implementing all the banners. The general banner (the one that shows the profile name) gets covered by the GitHub banner, and the YouTube banner covers the GitHub banner. If I try to fix this, it would make the PR too big, since I would have to also modify the GitHub styling, as well. I can file an issue so we can focus on this only. What do you think?

2022-03-25 14:34 UTC, Kevan-Y commented
> > When scrolling down, the yourubeInfo component is hiding user/org. ![image](https://user-images.githubusercontent.com/58233223/160139463-03f56480-9eb0-4ca0-8731-cd24e71e9d1c.png)
> 
> I actually noticed this when I was writing the PR, and the main problem is how we are currently implementing all the banners. The general banner (the one that shows the profile name) gets covered by the GitHub banner, and the YouTube banner covers the GitHub banner. If I try to fix this, it would make the PR too big, since I would have to also modify the GitHub styling, as well. I can file an issue so we can focus on this only. What do you think?

OK file an issue on that, and we can merge that

2022-03-25 14:34 UTC, Kevan-Y approved these changes

2022-03-25 16:08 UTC, merged