Parser docker
Seneca-CDOT/telescope pull request #3302
Opened 2022-03-24 01:07 UTC by TueeNguyen

## Issue This PR Addresses
Fixes #2111 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Revert all commented parser's docker code
- Add code to fit in with recent docker changes
- Rework parser's docker file to better practice

## Steps to test the PR
- `pnpm services:start`
- go to `localhost:8000` AND THAT'S ALL YOU NEED, NO `pnpm start`

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-03-24 01:40 UTC, TueeNguyen commented
Wait for #3040 to merge first

2022-03-24 02:14 UTC, TDDR requested changes

2022-03-24 02:14 UTC, TDDR commented on docker/production.yml
> +    image: docker.cdot.systems/posts:${DOCKER_DEPLOY_TAG:-latest}
should be `parser` instead of `posts`

2022-03-24 13:13 UTC, Kevan-Y requested changes

2022-03-24 13:13 UTC, Kevan-Y commented on src/api/parser/Dockerfile
> +ENV PORT=10000
I think we can replace to `PARSER_PORT`
```suggestion
ENV PARSER_PORT=10000
```

2022-03-24 13:13 UTC, Kevan-Y commented
Image size compare to before
```bash 
❯ docker images | grep refactor/parser
refactor/parser                                 old                de119410c427   14 seconds ago       185MB
refactor/parser                                 new                5efd1346e57b   About a minute ago   170MB
```

2022-03-24 14:31 UTC, TueeNguyen commented
> Image size compare to before
> 
> ```shell
> ❯ docker images | grep refactor/parser
> refactor/parser                                 old                de119410c427   14 seconds ago       185MB
> refactor/parser                                 new                5efd1346e57b   About a minute ago   170MB
> ```

Small but good improvement

2022-03-24 14:53 UTC, humphd requested changes

2022-03-24 14:53 UTC, humphd commented on docker/development.yml
> +      - '10000:10000'
Why do we need a port open?  It's accessible via Traefik.

2022-03-24 14:53 UTC, humphd commented on docker/gitpod.yml
> +    ports:
Same question here.

2022-03-24 14:53 UTC, humphd commented on src/api/parser/Dockerfile
> +	CMD wget --no-verbose --tries=1 --spider localhost:${PORT}/healthcheck || exit 1
`PORT` should be `PARSER_PORT`

2022-03-25 01:12 UTC, humphd approved these changes

2022-03-25 05:09 UTC, merged