Refactor Dockerfile sso
Seneca-CDOT/telescope pull request #3307
Opened 2022-03-24 12:57 UTC by Kevan-Y

## Issue This PR Addresses
Fixes #1668

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

- Add multi-staging layers
- Add Docker Healthcheck
- Use a smaller base image

Image is a bit bigger because we install the pnpm package
```bash
❯ docker images | grep refactor/sso
refactor/sso                                    new                8656590ef009   5 minutes ago    155MB
refactor/sso                                    old                02baf2192da0   32 minutes ago   135MB
```

## Steps to test the PR

- `pnpm services:start`
- Go to `http://localhost/v1/auth/healthcheck`
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-03-24 13:06 UTC, humphd requested changes
Let's drop the dev/dependencies stuff, we don't need.

2022-03-24 13:06 UTC, humphd commented on src/api/sso/Dockerfile
> +## Dependencies-dev ###############################################################
I don't think we're actually using this pattern anywhere else, so maybe we should remove this.

2022-03-24 18:10 UTC, humphd approved these changes
Looks good

2022-03-24 18:11 UTC, Kevan-Y commented
Great, I'm gonna squash those commits.

2022-03-25 16:52 UTC, AmasiaNalbandian submitted a review, later dismissed

2022-03-25 17:14 UTC, humphd requested changes
I can't build this on Mac (M1), I need python.

2022-03-25 18:14 UTC, Kevan-Y commented
> I can't build this on Mac (M1), I need python.

Using a bigger node image for the building part, I think it should work for M1.

2022-03-30 23:47 UTC, humphd commented
Let's get this rebased, there's been a lot of changes on the Dockerfiles recently.

2022-03-31 15:34 UTC, humphd commented
I can't see what's failing on CI, and I can't reproduce the failure locally.  I'm stumped.

2022-04-06 02:19 UTC, Kevan-Y commented
This is so weird, 
I checked out this branch and ran my test case on CentOS, but the test case is passing.
![image](https://user-images.githubusercontent.com/58233223/161882417-04d52066-c973-443e-9d6a-b044832cd629.png)

2022-04-06 13:27 UTC, humphd commented
Really interesting.  I wonder what we're hitting?  Maybe it's as simple as resource issues, but I can't understand how either PR would affect it.  These are running on a VM with 2 vCPU and 7 GiB of memory.

I wonder if we're crashing the login container or something, but that wouldn't explain why subsequent tests on other browsers work.

We need to get more creative with our thinking...

2022-04-06 14:45 UTC, humphd commented
This is what's running in that test: https://github.com/Seneca-CDOT/telescope/blob/a037690f2f55a7cb763e064b85dd4136ffec5e39/src/api/sso/test/e2e/browser-util.js#L14-L42

I wonder if we should add a bunch of logs so we can see where in the test it's getting stuck.

It could also be somehow related to https://github.com/Seneca-CDOT/telescope/blob/a037690f2f55a7cb763e064b85dd4136ffec5e39/src/api/sso/test/e2e/supabase-util.js#L8-L45

2022-04-06 15:32 UTC, Kevan-Y commented
> @Kevan-Y @JiaHua-Zou can we summarize what we know about this failure here?

Failing in Github actions in `FAIL browser: chromium src/api/sso/test/e2e/auth-flows.test.js - Login flow preserves state param (25227 ms)`

Environment tested locally:
**Windows 11 pro 21H2** - test case pass.
**Windows 11 pro 21H2 on WSL2 Ubuntu-20.04** - test case pass
**Amazon Linux 2 AMI (HVM) - Kernel 5.10 (ami-0c02fb55956c7d316 (64-bit x86)) - t2.large** - test case pass 
**MacOS M1**, test case pass @humphd

2022-04-06 15:35 UTC, Kevan-Y commented
> This is what's running in that test:
> 
> https://github.com/Seneca-CDOT/telescope/blob/a037690f2f55a7cb763e064b85dd4136ffec5e39/src/api/sso/test/e2e/browser-util.js#L14-L42
> 
> I wonder if we should add a bunch of logs so we can see where in the test it's getting stuck.
> 
> It could also be somehow related to
> 
> https://github.com/Seneca-CDOT/telescope/blob/a037690f2f55a7cb763e064b85dd4136ffec5e39/src/api/sso/test/e2e/supabase-util.js#L8-L45

Will try this and see what is the place that is stuck

2022-04-07 13:01 UTC, Kevan-Y commented
Converting PR into a draft while I'm debugging the fail test case.

2022-04-11 19:48 UTC, humphd submitted a review, later dismissed
Great work not giving up on this.

2022-04-11 20:00 UTC, Kevan-Y commented
@humphd, sorry to make you re-review again, this is the right change with pnpm + adding Docker best practices

2022-04-11 22:13 UTC, humphd approved these changes

2022-04-11 22:34 UTC, humphd commented
This i ready to go, just needs one more r+

2022-04-11 22:41 UTC, aserputov approved these changes

2022-04-11 22:42 UTC, merged