added portainer and supabase prod/staging links to sidebar
Seneca-CDOT/telescope pull request #3401
Opened 2022-04-05 16:00 UTC by joelazwar

## Issue This PR Addresses
closes #3380

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Adds staging/production links for Portainer and Supabase on our status page sidebar

## Steps to test the PR

### Using Docker

- `pnpm services:clean`
- `pnpm services:start status`
- Navigate to `localhost:1111`

### Without Docker
- `cd src/api/status`
- `pnpm install`
- `pnpm dev`
- Navigate to `localhost:1111`

Check sidebar for new links

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-04-05 16:06 UTC, tcvan0707 submitted a review, later dismissed

2022-04-05 20:37 UTC, humphd requested changes

2022-04-05 20:37 UTC, humphd commented on src/api/status/src/views/partials/sidebar.hbs
> +        <a class="nav-link text-white" href="https://dev.supabase.telescope.cdot.systems/">
Remove `dev.`

2022-04-06 02:04 UTC, tcvan0707 approved these changes

2022-04-06 02:09 UTC, humphd approved these changes

2022-04-06 19:50 UTC, merged