Drop default hash value
Seneca-CDOT/telescope pull request #3474
Opened 2022-04-12 19:04 UTC by DukeManh

## Issue This PR Addresses

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

## Steps to test the PR

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-04-12 19:28 UTC, TueeNguyen commented on src/db/prisma/schema.prisma
> +  id                 String  // A short hashed id generated from the URL be Satellite,
I don't understand this `from the URL be Satellite`

2022-04-12 19:31 UTC, TueeNguyen submitted a review, later dismissed

2022-04-12 19:32 UTC, tcvan0707 approved these changes

2022-04-12 19:36 UTC, TueeNguyen commented
I guess the some sso tests fails because of the new `hash` change?

2022-04-12 19:42 UTC, JerryHue approved these changes

2022-04-12 19:59 UTC, JerryHue requested changes

2022-04-12 19:59 UTC, JerryHue commented on src/api/sso/test/e2e/supabase-util.js
> +        id: hash(normalizeUrl(feed)),
As per CI:
```suggestion
        id: hash(normalizeUrl(feed.url)),
```

2022-04-12 20:50 UTC, humphd commented
> I guess the some sso tests fail because of the new `hash` change?

Ah, so this is why we're breaking!

2022-04-12 21:24 UTC, DukeManh commented
I was away to push the new commit, the tests should pass now.

2022-04-12 21:29 UTC, DukeManh commented
@humphd, the checks from you pr should be a different thing because the `id` is optional for now.

2022-04-12 21:33 UTC, humphd commented
Except you're failing the same test as I am:

```
 ✕ signup flow works to login and register a new Telescope user (20215 ms)
    ✓ signup flow fails if user is not authenticated (130 ms)
    ✓ signup flow fails if user data is missing required properties (807 ms)
    ✓ signup flow fails if user is already a Telescope user (672 ms)
    ✓ Signup flow fails if feed is already used by another Telescope user (1346 ms)

  ● Signup Flow › signup flow works to login and register a new Telescope user

    thrown: "Exceeded timeout of 20000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      64 |     ensureUsers(users, false));
      65 |
    > 66 |   it('signup flow works to login and register a new Telescope user', async () => {
         |   ^
      67 |     // Part 1: login using SSO, as a user who does not have a Telescope account.
      68 |     // Confirm that the payload of the token we get back matches what we expect.
      69 |     // NOTE: the data comes from config/simplesamlphp-users.php.

      at src/api/sso/test/e2e/signup-flow.test.js:66:3
      at Object.<anonymous> (src/api/sso/test/e2e/signup-flow.test.js:46:1)
```

2022-04-12 21:35 UTC, DukeManh commented
Now we share the error. What's going on.

2022-04-12 21:40 UTC, humphd commented
I blame @Kevan-Y

2022-04-14 20:59 UTC, humphd approved these changes

2022-04-14 21:36 UTC, TueeNguyen approved these changes

2022-04-14 21:38 UTC, merged