Make parser arg optional, rename main function for github-url-parser
Seneca-CDOT/telescope pull request #3492
Opened 2022-04-15 15:14 UTC by humphd

I need to make a few tweaks to the API.

2022-04-18 19:11 UTC, DukeManh approved these changes
That e2e test again.

2022-04-18 19:17 UTC, humphd commented
> That e2e test again.

Filed https://github.com/Seneca-CDOT/telescope/issues/3504.  We need to solve this.

2022-04-18 20:06 UTC, humphd commented
I'm doing a test to see if I can get more details about this failure.  I'll undo these changes.

2022-04-18 22:32 UTC, humphd commented
Can I get some reviews on this so I can build on it?  We're all clear on CI

2022-04-18 23:23 UTC, menghif requested changes

2022-04-18 23:23 UTC, menghif commented on src/github-url-parser/test/index.test.js
>  describe('githubUrlParser', () => {
`parseGitHubUrls` here too.

2022-04-18 23:25 UTC, humphd commented on src/github-url-parser/test/index.test.js
>  describe('githubUrlParser', () => {
Fixed.

2022-04-18 23:26 UTC, menghif approved these changes

2022-04-19 03:51 UTC, DukeManh approved these changes

2022-04-19 13:06 UTC, merged