Add Twitch sign-up page
Seneca-CDOT/telescope pull request #3505
Opened 2022-04-18 20:42 UTC by menghif

## Issue This PR Addresses

Fixes #2843 - Work in progress

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

I originally planned with @tcvan0707 to add a Youtube and Twitch field under the Blog RSS page but it ended up looking crowded and difficult to understand.

This PR adds a new page in the signup flow for the 2 optional Youtube and Twitch fields.

<img width="554" alt="Screen Shot 2022-04-18 at 4 31 20 PM" src="https://user-images.githubusercontent.com/53121061/163873796-1b4ef2ec-b8bd-4174-85bf-a93ebf893228.png">

## Steps to test the PR

- `pnpm services:start`
- `cd src/db`
- `cp env.example .env`
- `pnpm migrate`

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-04-19 15:56 UTC, menghif commented on src/web/app/src/components/SignUp/Forms/YoutubeTwitchFeeds.tsx
> +              name={twitchUrl.name}
Good idea, I changed everything to use the word `channel`.

2022-04-19 16:07 UTC, humphd requested changes

2022-04-19 16:07 UTC, humphd commented on src/web/app/src/components/SignUp/Forms/ChannelFeeds.tsx
> +              helperText={channelUrlError || 'Validate your Youtube or Twitch URL(s)'}
YouTube (capital 'T')

2022-04-19 16:07 UTC, humphd commented on src/web/app/src/components/SignUp/Schema/FormModel.tsx
> +    label: 'Youtube/Twitch URL(s)',
YouTube

2022-04-20 03:19 UTC, tcvan0707 commented
I am thinking we should include the YouTube/Twitch links on the Review page too

2022-04-20 13:23 UTC, menghif commented
> I am thinking we should include the YouTube/Twitch links on the Review page too

They are included.

2022-04-20 14:44 UTC, tcvan0707 approved these changes

2022-04-20 15:01 UTC, merged