Get correct display_name for feeds
Seneca-CDOT/telescope pull request #3663
Opened 2022-09-28 15:29 UTC by RC-Lee

## Issue This PR Addresses
Fixes #3660 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue

## Description

I used my old pal `console.log` to see the structure of the feeds that we were pulling from the db.
Turns out there wasn't any `display_name` property with each `feed` object.
```terminal
data structure is: 
 [
  {
    wiki_author_name: 'David Humphrey',
    url: 'http://blog.humphd.org/tag/seneca/rss',
    telescope_profiles: null
  },
  {
    wiki_author_name: null,
    url: 'https://dev.to/feed/rclee',
    telescope_profiles: { display_name: 'Roxanne Lee' }
  }
]
```

## Steps to test the PR
Testing locally is a bit complicated.
1. I changed [src/db/seed/feeds.json](https://github.com/Seneca-CDOT/telescope/blob/master/src/db/seed/feeds.json) to have only 1 feed (for simple testing purposes)
```js
[
  {
    "url": "http://blog.humphd.org/tag/seneca/rss",
    "user_id": null,
    "wiki_author_name": "David Humphrey",
    "html_url": null,
    "type": "blog",
    "invalid": false,
    "flagged": false,
    "id": "a2029d1f3e"
  }
]
```
2. After deleting any redis cache and doing db migration, I went to http://localhost:8910/ ,where the local db console was, to manually add myself a Telescope profile, and linked it to a Feed, making sure I kept `wiki_author_name` as `NULL`

3. Tested to make sure that before the fix my blogs wouldn't show up. (They did not)

4. Tested after the fix, and made sure my blogs showed up (They did)

We won't be able to see the fix on staging cause staging has nothing in the `telescope_profiles` table

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not

2022-09-28 15:34 UTC, humphd requested changes
Amazing, thank you!

2022-09-28 15:34 UTC, humphd commented on src/api/parser/src/utils/supabase.js
> +      author:
Let's use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to simplify this a bit:

```js
author: feed.telescope_profiles?.display_name || feed.wiki_author_name,
```

2022-09-28 15:49 UTC, humphd submitted a review, later dismissed

2022-09-28 15:50 UTC, RC-Lee commented
I was wondering if we could wait a few days until hacktoberfest kicks off,
But its also fine if we want to get this in asap.

2022-09-28 15:51 UTC, humphd commented
I'm fine to wait 🎃

2022-10-01 01:13 UTC, DukeManh submitted a review, later dismissed
This is the correct way to get `display_name`, I also see it in `src/api/planet/src/util.js`

https://github.com/Seneca-CDOT/telescope/blob/efff34f3bb983c8e43bdcfdf05602bc471019712/src/api/planet/src/util.js#L88

2022-10-01 01:29 UTC, humphd commented
@RC-Lee are you willing to fix the planet code at the same time?

2022-10-02 15:32 UTC, humphd approved these changes

2022-10-02 15:37 UTC, merged