Fixes #3686 Adding Mandarin(traditional Chinese) translation to About US page
Seneca-CDOT/telescope pull request #3698
Opened 2022-10-08 05:00 UTC by cychu42

## Issue This PR Addresses
Fixes #3686 

## Type of Change
- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This adds a Mandarin(traditional Chinese) translation to About US page(`overview.md`), and it also lists this translation to `docusaurus.config.js`.

## Steps to test the PR

Please navigate to `src/web/docusaurus/docs/overview.md` to find the `overview.md` document.

## Checklist

- [ x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-10-08 18:35 UTC, RC-Lee requested changes
Translating stuff is rough, so let's discuss and start with this. 
Basically
- For "open source" it might be fine to keep it just as "open source", but if we had to translate it, "開源" is fine in most cases, instead of "開源軟體"
- Front-end and Back-end should be "前端" and "後端"
- Some stuff I think are better left just as English 

Like I said, open for discussion, cause I'm not sure if we'll get a second reviewer.

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 重寫前臺的TypeScript。
```suggestion
- 以TypeScript重寫前端。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 手動和自動(Dependabot)依賴更新和維護。
```suggestion
- 手動和自動(Dependabot)更新和維護依賴關係。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +Seneca的開源軟體開發其中一個關鍵的特色是重視分享我們正在做些甚麼、教育，以及藉由部落格發文來學習。
```suggestion
Seneca的開源開發計畫其中一個關鍵的特色是藉由部落格發文來重視分享我們正在做些甚麼、進行的教育，以及所受的學習。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +我們相信學習如何在開源軟體社群中作業最具獎勵的一部分是發現自己能夠成為網路的一份子、找到自己的聲音和建立一些追隨。
```suggestion
我們相信學習如何在開源社群中作業最具獎勵的一部分是發現自己能夠成為網路的一份子、找到自己的聲音和建立一些追隨。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +一個將Seneca開源軟體開發的師生所發表的部落格文章化成單頁的集合體。
```suggestion
一個將開源開發的Seneca師生所發表的部落格文章化成單頁的集合體。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +在2000年代的早期，在像推特和臉書等社群軟體的崛起前，Planet解決了一個開源軟體社群的重要問題。
```suggestion
在2000年代的早期，在像推特和臉書等社群軟體的崛起前，Planet解決了一個開源社群的重要問題。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +我們現在的Planet正在消亡中。我們用的軟體最後更新是13年前。當內含的程式碼正在往過去飄去，
```suggestion
我們現在的Planet正在消亡中。我們用的軟體最後更新是13年前。當內含的程式碼正在隨著時間流逝成為過去式，
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +我們的需求依然前進著。特別是因為在Seneca參予開源軟體開發的學生數量，維護既有的程式碼變得相當地困難。
```suggestion
我們的需求依然前進著。特別是因為在Seneca參予開源開發的學生數量，維護既有的程式碼變得相當地困難。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 一個單體式node.js後臺網路伺服器提供REST APIs和GraphQL。
```suggestion
- 一個提供REST APIs和GraphQL的單體式node.js後端網路伺服器。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 一個用於摘要平行處理的node.js排隊服務。
```suggestion
- 一個用於摘要平行處理的node.js佇列服務。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 一個使用Material UI React部件的GatsbyJS前臺網路伺服器。
```suggestion
- 一個使用Material UI React部件的GatsbyJS前端網路伺服器。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 初步SAML2基礎的單一登入認證。　
```suggestion
- 以SSO認證初始化SAML2
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 使用CircleCI和Travis CI的CI/CD管道。
```suggestion
- 使用CircleCI和Travis CI的CI/CD pipeline。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 使用Zeit Now的合併請求預覽。
```suggestion
- 使用Zeit Now的Pull Request預覽。 
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- GitHub推事件和webhooks的部屬，以自動化整裝和生產軟體組建，包含藍綠部署。
```suggestion
- GitHub push event和webhooks的部屬，以自動化整裝和生產軟體組建，包含green/blue deployment。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 整裝(<https://dev.telescope.cdot.systems/>)和生產(<https://telescope.cdot.systems/>)部署。
```suggestion
- Staging (<https://dev.telescope.cdot.systems/>)和Production(<https://telescope.cdot.systems/>)部署。
```

2022-10-08 18:35 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 使用Traefik遷移單體式後臺到Microservices(90%完成)和API Gateway。
```suggestion
- 使用Traefik遷移單體式後端到Microservices(90%完成)和API Gateway。
```

2022-10-08 18:53 UTC, RC-Lee requested changes

2022-10-08 18:53 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- [Telescope 3.0](https://blog.humphd.org/toward-telescope-3-0/) (製作中，2020年四月)
```suggestion
- [Telescope 3.0](https://blog.humphd.org/toward-telescope-3-0/) (製作中，2022年四月)
```

2022-10-11 18:14 UTC, cychu42 commented
I initially felt the need to specify 軟體(software) in cases the term open source is used in other context, but I guess it’s pretty exclusive to software?
Another reason being that anyone who’s not familiar with open source or just programming in general in Mandarin can tell it’s about some kind of software.

As for "前端" and "後端" vs "前臺" and "後臺", I have seen both ways so I think it’s fine either way.

2022-10-11 18:20 UTC, cychu42 commented on src/web/docusaurus/docs/overview.md
> +Seneca的開源軟體開發其中一個關鍵的特色是重視分享我們正在做些甚麼、教育，以及藉由部落格發文來學習。
I'm not sure about 所受的學習, because I don't think you passively "receive" learn from other sources. You actively learn.

2022-10-11 18:38 UTC, cychu42 commented on src/web/docusaurus/docs/overview.md
> +- 初步SAML2基礎的單一登入認證。　
If it's 初始化, shouldn't the original english text say "Initialize"? Instead, the original says "Initial".

2022-10-11 18:50 UTC, cychu42 commented
Lastly, I'm not opposed to leaving some of those technical terms in English as you suggested, especially if you have experience with their convention in Mandarin. It’s not unheard of to just use the English terms for Mandarin speakers, when it comes to specialized terms.
I'm not entirely familiar with the convention for how some of the terms are translated, so I had to do a bit of digging around the internet to see how people refer to them in Mandarin. 合併請求 and 藍綠部署 show up a few times, so I’m inclined to say we can keep them, but rest of the terms you pointed out might be better left in English as you said.

2022-10-11 19:13 UTC, RC-Lee commented
> Lastly, I'm not opposed to leaving some of those technical terms in English as you suggested, especially if you have experience with their convention in Mandarin. It’s not unheard of to just use the English terms for Mandarin speakers, when it comes to specialized terms. I'm not entirely familiar with the convention for how some of the terms are translated, so I had to do a bit of digging around the internet to see how people refer to them in Mandarin. 合併請求 and 藍綠部署 show up a few times, so I’m inclined to say we can keep them, but rest of the terms you pointed out might be better left in English as you said.

I trust your research, so if you've seem them around a lot, then yes please do keep them as is. 
You seem to be missing a configuration on this line here in your PR. 
https://github.com/Seneca-CDOT/telescope/blob/76609baa6d2f52974ab3101eff0319890ec7532c/src/web/docusaurus/docusaurus.config.js#L44
Please also rebase when you're ready for review.

2022-10-12 16:49 UTC, RC-Lee commented on src/web/docusaurus/docs/overview.md
> +- 初步SAML2基礎的單一登入認證。　
Makes sense. 
Its just the original sentence seems a little bit off to me.
What do you think of something like
```suggestion
- 開始以SAML2為基礎的SSO。　
```
If you think "初步" is better than "開始", then I guess keep it like that (maybe I haven't used Mandarin in too long :P).
I have a feeling "SSO" is better known than "單一登入認證", but if you want to keep it, maybe put it like "單一登入認證(SSO)"?

2022-10-12 22:18 UTC, cychu42 commented
Thank you for the review and suggestions. This is now ready for re-review.
I decided to keep 開源軟體 and implemented the changes we talked about.
I did change 合併請求 to 拉取請求, because the former actually means “merge request” (my bad!), while the later is how pull request is called.

2022-10-12 22:46 UTC, RC-Lee commented
The PR doesn't pass our CI, prettier specifically, please resolve them first.

2022-10-13 00:07 UTC, cychu42 commented
I managed to resovle the issue with Prettier.

2022-10-13 02:39 UTC, RC-Lee commented
Translations look fine. 
Pinging Docusaurus peeps for build related stuff 

cc: @sirinoks @cindyledev

2022-10-13 12:46 UTC, cychu42 commented
I'm looking at past translation PRs and the current project structure, I think that would be the general location.
However, I think you would want to put it under either a zh-cht folder for traditional Chinese or zh-tw folder for traditional Chinese (Taiwan). The zh-cn folder would be for simplified Chinese (China) instead.

2022-10-13 12:58 UTC, sirinoks commented on src/web/docusaurus/docs/overview.md
> +# Telescope 總覽
Looking at #3701 which worked out - yes. I think it has to be in the /i18n. The main one changed the original file. 

Just ran the build to check. You are correct. This is wrong. 
As you can see, the original English page changed to Chinese:
![image](https://user-images.githubusercontent.com/13803161/195602556-5936f21d-1c25-4e6b-9f0a-548b8a37c73d.png)

And the Chinese page is non existant:
![image](https://user-images.githubusercontent.com/13803161/195602322-45054bc5-f691-4353-8ca5-beb33d183f56.png)

2022-10-13 13:01 UTC, sirinoks requested changes
Look at #3701 

Instead of changing the 
`src/web/docusaurus/docs/overview.md`

Change, or create yourself if you have to
`src/web/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current/overview.md`

To test, also look at the "Steps to test PR". Just change uk to zh when npm start-ing

2022-10-13 13:46 UTC, cychu42 commented
OK. I reverted `src/web/docusaurus/docs/overview.md` to the original and moved my translation to `src/web/docusaurus/i18n/zh/docusaurus-plugin-content-docs/current/overview.md` instead, as requested.
Please let me know if you need anything else.

2022-10-13 17:30 UTC, manekenpix approved these changes
LGTM :+1: 

![image](https://user-images.githubusercontent.com/23108901/195665621-d921712f-d813-42de-9eb9-5c8e19cc356b.png)

2022-10-13 17:36 UTC, RC-Lee approved these changes
Built. Works.
![image](https://user-images.githubusercontent.com/32626950/195666740-250bde42-3d1c-42d5-becd-7fae59492cdb.png)

2022-10-13 17:37 UTC, cindyledev approved these changes

2022-10-13 17:39 UTC, merged