Added Ukrainian translation for About page
Seneca-CDOT/telescope pull request #3701
Opened 2022-10-08 20:34 UTC by devils2ndself

## Issue this PR addresses
Resolves https://github.com/Seneca-CDOT/telescope/issues/3699

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR is Ukrainian translation for the Docusaurus About page.

![image](https://user-images.githubusercontent.com/71770433/194726844-f8942280-5f53-464c-a51f-f1c1c72c0537.png)

![image](https://user-images.githubusercontent.com/71770433/194726857-3d996151-f70a-4f2e-99f8-0e7f5d43893c.png)

![image](https://user-images.githubusercontent.com/71770433/194726868-aa26fbec-a9d9-4bcc-83ab-80f1d1e0a8a5.png)

## Steps to test the PR

- `cd src\web\docusaurus`
- `npm install`
- `npm run start -- --locale uk`
- Click 'Docs' button top left corner

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-10-10 04:40 UTC, sirinoks commented
The environment runs, no errors, nothing broken.

2022-10-10 04:41 UTC, sirinoks requested changes
Please review my comments and implement small fixes.

Otherwise - the environment runs, nothing is broken.

2022-10-10 04:41 UTC, sirinoks commented on src/web/docusaurus/i18n/uk/docusaurus-plugin-content-docs/current/overview.md
> +Рузультат Telescope був досягнутий, завдяки сумісній праці усіх цих талановитих людей (та роботів).
Typo:

> Рузультат

Р**е**зультат

2022-10-10 04:41 UTC, sirinoks commented on src/web/docusaurus/i18n/uk/docusaurus-plugin-content-docs/current/overview.md
> +Задля кращого виявлення блогів у нашій спільноті, ми встановили блог з відкритим кодом під назвою "[Planet](<https://en.wikipedia.org/wiki/Planet_(software)>)" – агреговану
> Planet

Не помилка, та можливо є сенс таки перекласти Планету. Бо ми пояснюємо нижче що це значить anyways.

Just consider this, you may disagree, just let me know what you think is best.

2022-10-10 04:41 UTC, sirinoks commented on src/web/docusaurus/i18n/uk/docusaurus-plugin-content-docs/current/overview.md
> +Загалом, Telescope приймає [RSS стрічки публікацій блогів](https://rss.com/blog/rss-feed-for-blog/), перебудовує ці дописи у формат HTML і збирає їх у єдину веб-сторінку для відображення. Він здатний
> Дописи в блогах на Telescope надходять від учасників Telescope

This sentence makes no sense. Needs rephrasing

2022-10-10 18:03 UTC, devils2ndself commented on src/web/docusaurus/i18n/uk/docusaurus-plugin-content-docs/current/overview.md
> +Задля кращого виявлення блогів у нашій спільноті, ми встановили блог з відкритим кодом під назвою "[Planet](<https://en.wikipedia.org/wiki/Planet_(software)>)" – агреговану
Я думав про це, але вирішив залишити латинською усюди, де мається на увазі сам додаток, а там, де виходить гра слів і мова йде не про сам додаток (а про його альтернативи), перекласти

Звісно ж можу змінити, але мені здається, що так контекстуально правильніше, let me know what you think

2022-10-10 18:14 UTC, devils2ndself commented on src/web/docusaurus/i18n/uk/docusaurus-plugin-content-docs/current/overview.md
> +Загалом, Telescope приймає [RSS стрічки публікацій блогів](https://rss.com/blog/rss-feed-for-blog/), перебудовує ці дописи у формат HTML і збирає їх у єдину веб-сторінку для відображення. Він здатний
Changed to "Публікації, які можна побачити на Telescope, надходять з блогів учасників розробки."

Let me know if you think it should be rephrased into something different

2022-10-11 03:43 UTC, sirinoks approved these changes
Looks good!

2022-10-11 03:52 UTC, merged