Added Russian translation of the overview docs page
Seneca-CDOT/telescope pull request #3765
Opened 2022-11-17 04:53 UTC by gulyapulya

## Issue This PR Addresses

Fixes #3705

Part of  #2962 which combines all translations

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR adds Russian translation for the overview page of docs.

Examples:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/52351598/202358428-7f62b443-606f-4d00-9006-97ef03f72000.png">

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/52351598/202358574-55bbb8a4-ac4f-4533-befb-a11ebfe93b77.png">

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/52351598/202358677-9a9f580e-cb50-4de1-a294-f75ee6702828.png">

## Steps to test the PR

- cd src\web\docusaurus
- npm install
- npm run start -- --locale ru
- Click 'Docs' button top left corner

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

2022-11-17 05:01 UTC, gulyapulya commented
Hi @sirinoks, could you please review this PR? (you said you can check Russian translations)

Sorry for being late on the issue #3705... I had enough PRs for Hacktoberfest, but came back for it now.  :)

2022-11-18 05:25 UTC, IvaniGabrovsky commented
I got a Russan speaker to review the Russian language. Everything looks good and ready to be merged.

2022-11-18 05:50 UTC, gulyapulya commented
Thanks, @IvaniGabrovsky for the review!

2022-11-18 05:50 UTC, gulyapulya commented
@sirinoks I guess your review is optional now, but still would be great to have 😊 Please let us know if you will be available.

2022-11-18 16:47 UTC, sirinoks requested changes
Good job! Mostly my comments are not about errors, but rather things to consider improving. Some are concrete changes/corrections though.

2022-11-18 16:47 UTC, sirinoks commented on src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
> +Готовясь войти в 2020 год, мы решили, что пора рассмотреть вопрос перехода на новую систему. К сожалению, почти каждая приходящая на смену Planet система сама становилась такой, что не может быть обс
> система сама становилась такой, что не может быть обслуживаемой

система становилась необслуживаемой/устаревшей/забытой/заброшенной

2022-11-18 16:47 UTC, sirinoks commented on src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
> +- TypeScript переписывает внешний интерфейс
> TypeScript rewrite of front-end

Тут имелось ввиду скорее
`Переписка внешнего интерфейса с использованием/с помощью TypeScript`

2022-11-18 16:47 UTC, sirinoks commented on src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
> +## Наши вкладчики
Как-то "вкладчики" не так звучит. Я пыталась найти как обычно переводят contributors в других местах, и нашла одно место [тут](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/main/README-RU.md#open-source-%D0%B8%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D1%82%D0%B8%D0%B2%D1%8B-%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%B8%D0%B1%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BE%D0%B2). Тут просто тупо переводят - контрибьюторы. Не знаю, что из двух лучше - оба варианта как-то не очень. Можно вообще забить, и перевести как "разработчики", или "наша команда". Но так не интересно, хоть, может, и красивее..

Let me know what you think of this

2022-11-18 20:40 UTC, gulyapulya commented on src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
> +sidebar_position: 0
Docusaurus produces an old version of the overview page (without the contributors part in the beginning). So, I copied from the overview itself as was done in the Ukrainian translation. I guess it should be the order of the translations, but I was not sure about that number as different translations either have 0 or 1.

2022-11-18 20:46 UTC, gulyapulya commented on src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
> +> Planet (перевод:Планета) — это приложение-агрегатор лент, предназначенное для сбора статей из блогов членов интернет-сообщества и отображения их на одной странице. Планета работает на веб-сервере.
Да, я тоже над этим думала, но я решила отталкиваться от приложение-агрегатор (оно), потому что Планета здесь не переводится, а используется как название. 

Yeah, I was thinking about that too, but I used "оно" intentionally as the most correct form would be to refer to the word it describes which is "приложение-агрегатор".

2022-11-18 20:53 UTC, gulyapulya commented on src/web/docusaurus/i18n/ru/docusaurus-plugin-content-docs/current/overview.md
> +## Наши вкладчики
Я вот тоже долго искала как назвать, потому что ни один из вариантов не был на 100 процентов верным, потому я наверно оставлю на англ и сделаю ремарку на перевод.

2022-11-18 21:02 UTC, gulyapulya commented
Thank you for the review @sirinoks! It was so great to discuss all these little uncertainties in the translation, as I tried to come up with the best version, but you never know until someone confirms.

2022-11-18 21:03 UTC, gulyapulya commented
I have implemented all the changes suggested, @humphd let me know what you think. 😊

2022-11-18 23:43 UTC, sirinoks approved these changes

2022-11-18 23:59 UTC, merged